### ISSUE TITLE
Build command doesn't listen to keyboard interrupt

### ISSUE THREAD

**Issue by queengooborg** [mdn/yari#6275] opened 2022-05-14 05:46 UTC
I've noticed that even after pressing ^C, and even after closing the terminal tab, the build command keeps on running.  To cancel a build, I have to find the process and force terminate it.

**Comment by tlylt** [comment] 2023-02-06 07:08
Hi @queengooborg, could you share how you know that the process keeps on running? Is it by inspecting something like the "Task manager" or?

**Comment by caugner** [comment] 2024-06-24 20:10
@queengooborg Are you still experiencing this issue? I cannot reproduce: Ran `yarn build:docs --locale en-us` and pressed CTRL+C when the buiding of files started, but it aborted as expected. I'm closing as "works for me" for now, but feel free to reopen if this still happens.

**Closed by caugner** 2024-06-24 20:10 UTC
Labels: p3, 🐌 idle, accepting PR, dx, idle
