### ISSUE TITLE
Search Bar Text Color 

### ISSUE THREAD

**Issue by CubeOfCheese** [mdn/yari#10495] opened 2024-02-12 06:22 UTC
### Summary

The big, central search bar on the main page #hp-search-input displays the typed text in black. The background is also black so it appears as if you are not typing. I tested in Firefox, Safari, and Vivaldi and both Safari and Vivaldi displayed the text, but in Firefox the text is not visible. It is black text on a black background.

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

1. Type in the large search bar in the center

### Expected behavior

Search Query Text should display in white.

### Actual behavior

The text is black, blending in with the background so it is unable to be seen.

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="992" alt="Screenshot 2024-02-11 at 10 18 17 PM" src="https://github.com/mdn/yari/assets/16740469/f95fd223-3c7c-4a09-b916-b334e2aaa01b">
<img width="992" alt="Screenshot 2024-02-11 at 10 18 28 PM" src="https://github.com/mdn/yari/assets/16740469/74be1bb2-cae6-4a99-878c-b3e3eda9fe0f">

### Anything else?

It looks like the nav search bar is using this property and the big search bar is not

```color: var(--text-primary);```

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by argl** [comment] 2024-02-13 16:34
Hi, thank you for reporting an issue. I just tried to reproduce this, but it is all working as expected, on a similar environment (what version of MacOs are you using?), same browser. 

Could you please try again and verify the issue is still valid? We did not receive any similar reports yet, so I am curious.

Thanks again for taking the time to report!

**Comment by CubeOfCheese** [comment] 2024-02-15 06:50
I'm surprised there haven't been similar reports. It affects all of my students computers in my computer lab. It's been like this for months, I just finally got around to reporting it. I'll get you version information when I get back in the lab in the morning

**Comment by argl** [comment] 2024-02-15 11:07
Could you please report what `about:support` in Firefox tells? You can use my github email address if you are concerned about leaking information. You can also restart Firefox from that page without extensions in _Troubleshooting Mode_, maybe it is some extension that gets in the way. Thanks!

**Comment by CubeOfCheese** [comment] 2024-02-15 16:13
Okay I think that uncovered the issue. The student's computers are running 89.0.2. I had to get around IT's managed install, but once I installed the current version 122.0.1, the search bar looked normal.

**Comment by argl** [comment] 2024-02-15 17:24
Ah good to hear! Closing this.

**Closed by argl** 2024-02-15 17:24 UTC
Labels: dark-mode, awaiting response
