### ISSUE TITLE
Compat table: prefixes not displayed

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/yari#2184] opened 2020-12-17 16:32 UTC
It looks like in the new compat tables, the prefixes themselves are not displayed; just that there is one:

<img width="606" alt="Screen Shot 2020-12-17 at 08 30 56" src="https://user-images.githubusercontent.com/5179191/102515120-31a75080-4042-11eb-8313-83c247273e5e.png">

(P.S. yes, I have a [custom dark theme](https://userstyles.org/styles/182570) -- I double-checked to make sure it's not a custom styling issue.)

**Comment by schalkneethling** [comment] 2020-12-17 16:33
Thank you for reporting @vinyldarkscratch 

Duplicate of https://github.com/mdn/yari/issues/2163

**Comment by vinyldarkscratch** [comment] 2020-12-17 16:34
Oops, apologies for the duplicate PR!  I forgot to check before writing this one... 😅

**Closed by schalkneethling** 2020-12-17 16:33 UTC
