### ISSUE TITLE
"appliesto" from mdn/data does not correctly render in {{CSSInfo}} macro

### ISSUE THREAD

**Issue by glmvc** [mdn/yari#10965] opened 2024-04-21 11:27 UTC
### Summary

[{{CSSInfo}} macro](kumascript/macros/CSSInfo.ejs) renders the `"appliesto"` string from [properties.json](https://github.com/mdn/data/blob/68d18c7907cfd19521ef414fac285dbc8dd0ffa1/css/properties.json#L1716) in [mdn/data](https://github.com/mdn/data) as is, so without commas and spaces between words and in camelCase.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/align-content#formal_definition

### Reproduction steps

Check the "Applies to" row in the rendered table.

### Expected behavior

Human readable text (comma separated with spaces between words and correct capitalization)

### Actual behavior

Text is the `"appliesto"` string from [properties.json](https://github.com/mdn/data/blob/68d18c7907cfd19521ef414fac285dbc8dd0ffa1/css/properties.json#L1716) in [mdn/data](https://github.com/mdn/data).

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Screenshot

![applies-to-issue](https://github.com/mdn/yari/assets/95487764/68a60f3e-a23f-41fa-80df-8e54bdfd4c52)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by glmvc** [comment] 2024-04-27 15:28
@caugner Indeed, I can no longer reproduce the error. It looks correct for me again.
I remember checking the site in Incognito and with cache disabled before filing the issue.

**Comment by argl** [comment] 2024-06-10 14:10
I am also not able to reproduce the issue, closing this out. If the problem resurfaces, feel free to re-open!

**Closed by argl** 2024-06-10 14:10 UTC
Labels: needs triage, idle
