### ISSUE TITLE
TypedArray "Try it" 502 error

### ISSUE THREAD

**Issue by Lakuna** [mdn/yari#6082] opened 2022-04-26 18:36 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The "Try it" section of all `TypedArray`-related pages contains a 502 error.

### What did you expect to see?

The "Try it" section should contain an interactive environment for trying out features related to `TypedArray`s.

### Do you have any supporting links, references, or citations?

![502](https://user-images.githubusercontent.com/31971465/165368911-0610c527-99f2-472b-a5ed-763f4b1705ce.png)

**Comment by schalkneethling** [comment] 2022-04-26 22:04
Closing as a duplicate of: https://github.com/mdn/yari/issues/6079 - Thank you for filing @Lakuna

**Closed by schalkneethling** 2022-04-26 22:04 UTC
Labels: 🧑‍🤝‍🧑 community, needs-triage
