### ISSUE TITLE
Code example component not rendering properly

### ISSUE THREAD

**Issue by BlackWind001** [mdn/yari#5589] opened 2022-03-12 10:32 UTC
### Summary

I was browsing the MDN docs when I noticed this issue with code examples.

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

### Reproduction steps

1. Go to the above mentioned URL on Firefox version 97.0,2
2.
3.

### Expected behavior

The expected behaviour is that the code component loads properly and is able to switch between HTML, CSS and JS snippets.

### Actual behavior

An unformatted example component is being rendered as if the styles and scripts related to it are not working as expected.

### Device

Laptop

### Browser

Firefox

### Browser version

Other version (specify below)

### Operating system

Windows

### Screenshot

![mdn-issue](https://user-images.githubusercontent.com/26765211/158014388-ded12ebb-b8b7-4498-aca5-37f9f2756256.PNG)

### Anything else?

I am using Firefox 97.0,2

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by BlackWind001** [comment] 2022-03-12 10:33
Note. This issue is not reliably reproducible.

**Comment by caugner** [comment] 2022-03-13 21:29
> Note. This issue is not reliably reproducible.

Quickly tried on Firefox for Android and couldn't reproduce it.

Some questions:

1. Did this also occur with other articles / interactive examples?
1. Were you able to reproduce it with another browser?
1. How often / regular did/does the problem appear approximately?
1. When it happens again, could you please check the browser's JavaScript console for any errors or warnings?

Thanks!

**Comment by caugner** [comment] 2022-03-14 09:28
I couldn't reproduce this on Firefox 98.0 (Desktop) either, so chances are this was just a networking issue or similar.

For now, I will close this issue, but don't hesitate to comment here (mentioning me), if the problem appears again, and make sure to answer the questions above then.

Thanks!

**Closed by caugner** 2022-03-14 09:28 UTC
Labels: bug, needs-triage, interactive-examples, need more info

**Comment by BlackWind001** [comment] 2022-03-14 09:34
Got it.
For additional information, I did check the console logs but did not have any distinct errors.
This issue persisted after a couple of refresh clicks though.
It did get fixed when I revisited the page.

It might have been a network issue, yes.
Will comment here if I notice this again.

Thanks.
