### ISSUE TITLE
T - Redirect to your locale

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#128] opened 2019-09-20 20:52 UTC
On MDN, today, if you go to `https://developer.mozilla.org/` (note the absence of a locale prefix on the path) the server dynamically picks a redirect for you. If there isn't a cookie, it has to use the `Accept-Language` request header. 
E.g
```
curl -v -H 'accept-language: sv-SE' https://developer.mozilla.org > /dev/null
...
< HTTP/2 301
< location: /sv-SE/
...
```

We won't have such a server in a static site so our only hope is to do this with JavaScript. (Assuming we want to keep the functionality!)

We won't be able to redirect with a proper 301 since loading `/index.html` will always `200 OK`. But on that page, we can trigger some JS code that looks at your `localStorage` and `navigator.language`. E.g.

```javascript
if (!isPrefixInCurrentURL()) {  // e.g. document.location.pathname == /
  // Unless overridden redirect to the user's preferred language
  const preferred = localStorage.getItem('preferredLanguage');
  if (preferred && validLanguage(preferred)) {
     triggerRouterRedirect(preferred);
  } else if (navigator.language && validLanguage(navigator.language)) {
      triggerRouterRedirect(navigator.language);
  } else {
    // Only bother if it's NOT the home page
    if (document.location.test(/\/docs\//) {
        triggerRouterRedirect('en-US');
    }
  }
}
```

For this to work, we'd need to have a hardcoded list of available locales in scope. I.e. that JavaScript can know.

**Comment by peterbe** [comment] 2019-09-20 21:15
Also, having to install https://addons.mozilla.org/en-US/firefox/addon/mdn-language-redirector/?src=search sucks. 
I.e. you're in France but you prefer to always read in en-US but you Google search for "IntersectionObserver" and the first hit is `https://developer.mozilla.org/fr/docs/Web/API/Intersection_Observer_API`. 
So if the user has a strong preference for a different locale perhaps we need to do a little check (based on localStorage) even if the current URL (document.location.pathname) *has* a locale prefix.

**Comment by tobinmori** [comment] 2020-07-21 17:50
- Depends on L10n decision.
- Orthongonally, always have to redirect to English

**Comment by peterbe** [comment] 2020-10-01 18:49
This is very much linked to https://github.com/mdn/yari/issues/275 which is about listening to the user's preferences and taking action.

**Comment by peterbe** [comment] 2020-10-30 19:11
@fiji-flo Did we fully resolve this? 
I think somewhere there lurks an issue about potentially redirecting to a different locale once you've arrived on a page that has a locale. But in general, I thought your Lambda@Edge work took care of this. Or?

**Comment by schalkneethling** [comment] 2021-11-02 14:49
dupe of https://github.com/mdn/yari/issues/275

**Closed by schalkneethling** 2021-11-02 14:49 UTC
Labels: localization, p1, deployment, redirects
