### ISSUE TITLE
Regression: New browser-compatibility table format is less helpful

### ISSUE THREAD

**Issue by MichaelAllenWarner** [mdn/yari#5366] opened 2022-03-01 14:36 UTC
The browser-compatibility table now displays just a checkmark if any version of the browser has adopted the feature in question, and you have to click the checkmark to see _which_ version was the earliest to adopt it. To be frank, this makes the table useless—developers now need to click every checkmark to glean the information they're looking for.

Please go back to the old way of displaying the _earliest_ version to adopt the feature.

**Comment by ConcernedHobbit** [comment] 2022-03-01 17:52
A great example from [HackerNews](https://news.ycombinator.com/item?id=30514280#30516381):
The [dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#browser_compatibility) browser compatability chart shows support for Firefox with a checkmark, leading developers to believe it is already supported.
However, support is shipping in FF98, which has not been released.

**Comment by alexkrolick** [comment] 2022-03-01 21:25
Another thing is that old design was screenshot-friendly. You could see all the version info in one go and paste it into a conversation. Now, since expanding one box collapses the current selection, you can't do that.

**Comment by arxpoetica** [comment] 2022-03-01 23:48
Came to just say the loss of color on the compatibility table makes it harder to scan. Green/yellow POPS (Hello, Wordle). Please add color back too.

**Comment by queengooborg** [comment] 2022-03-02 09:11
I'd have to agree with this -- while a checkbox, X, flask, etc. is much cleaner than numbers, it's a lot less helpful as well.  Additionally, the varying colors helped a lot with determining wide browser adoption at a glance.  I'd love to have the original tables brought back.

**Comment by gilmoreorless** [comment] 2022-03-02 11:14
A while ago I raised https://github.com/mdn/kumascript/issues/1384 in the now-archived predecessor to this project. I had been contemplating re-raising it here before the UI revamp. But I'd much prefer to have the previous display tables back (including that slightly misleading display) than the current simplified view.

Others have already stated some of the problems here, which I also agree with. For me the biggest thing is that the old display of versions conveyed a lot more information than a simple "yes/no" binary question.

To show a solid example, the `Intl.DateTimeFormat` options:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/159415/156348453-a65414cc-9244-461e-8915-cdb6b3db3fb3.png">

In the [old design](https://web.archive.org/web/20220118060844/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat), I could see at a glance that the `dateStyle` option was fairly-well supported. But the `dayPeriod` option, although supported, was _much_ newer and may not actually be available to all of my end users. See https://css-tricks.com/evergreen-does-not-mean-immediately-available/ for why this distinction is still really important, even in a world of auto-updating browsers.
It also shows a Node.js version of `12.9.0` — that minor version number is crucial information, as just running "Node 12" doesn't guarantee you have the option available.

By contrast, this is what [the page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#browser_compatibility) looks like today:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/159415/156349016-d101dd9d-e713-42c4-be7f-cae08e8c347a.png">

All of that extra contextual information is gone, leaving me clicking box after box after box after box to work out if I actually can use the feature. And on my 13" laptop screen, the last column is completely cut off due to the fairly limited space of the centre column in the new layout.

----

Also on that support table, backing up what was mentioned in https://github.com/mdn/yari/issues/5366#issuecomment-1055701516:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/159415/156349800-214fd666-acc2-4fc7-a2f1-64cd85decbc0.png">

Looks like good support in Safari for these options (6th column of icons). Now let's check which versions just to be sure...

<img width="431" alt="image" src="https://user-images.githubusercontent.com/159415/156350572-f86ce061-7957-43af-aac2-ef053938c74b.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/159415/156350611-83f2a9f3-d954-423e-b9d5-7fdb59da73db.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/159415/156350651-f0576762-e3d1-4a29-b40d-fbd6e01fe703.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/159415/156350704-4835ba5e-d422-462e-b22a-ecb33a145e0f.png">

That last item has a key difference that should be more visible. And at the time of writing, Safari 15.4 hasn't even been released yet.

**Comment by pleunv** [comment] 2022-03-03 11:36
Also baffled by the removal of the numbers on the default view. I think both the version numbers *and* the background colors are just too valuable to hide and/or remove. Quite frankly, even the browser icons add to the "glanceability". Less is definitely not more here.

**Comment by HerminaC** [comment] 2022-03-03 13:57
Thanks everyone for the feedback - we'll address this before the end of the week. @schalkneethling - let's use this ticket to track the BCD work

**Comment by j-f1** [comment] 2022-03-03 20:45
Another bit of feedback (let me know if this should be a new issue): features incorrectly say they’ve been “removed“ if a browser goes from partial to full support. Example: [`Notification.requestPermission`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission#browser_compatibility) in Safari
<img width="345" alt="Screenshot_2022-03-03 15 45 17" src="https://user-images.githubusercontent.com/25517624/156649980-9dd8bf26-c25b-4d58-858f-3f87848bd267.png">

**Comment by debiru** [comment] 2022-03-04 01:08
I am one of the MDN contributors, and I am feeling inconvenienced.

I understand that this will be supported, but one thing I would like to add is that when making such a design change, I would like to see the ability to revert to the previous design on a per-user basis at the same time. This problem has already been a hindrance to my work as an MDN contributor.

**Comment by schalkneethling** [comment] 2022-03-04 08:00
> 

That sounds like a separate issue.

**Comment by schalkneethling** [comment] 2022-03-04 08:01
> I am one of the MDN contributors, and I am feeling inconvenienced.
> 
> I understand that this will be supported, but one thing I would like to add is that when making such a design change, I would like to see the ability to revert to the previous design on a per-user basis at the same time. This problem has already been a hindrance to my work as an MDN contributor.

I am really sorry to hear that @debiru. We are working on giving you a way to switch back to the table showing version numbers and have it stick across page loads and navigation.

**Comment by yume-chan** [comment] 2022-03-04 08:07
> <img alt="Screenshot_2022-03-03 15 45 17" width="345" src="https://user-images.githubusercontent.com/25517624/156649980-9dd8bf26-c25b-4d58-858f-3f87848bd267.png">

The old version looked like this:

![image](https://user-images.githubusercontent.com/1330321/156723692-8ad59274-b2e7-40a2-8c6d-836272f7f0ae.png)

They have same data, but the new view displays them in a confusing way.

"Removed in 15 and later", "Partial support", "Only supported the deprecated callback syntax." are notes of the old implementation in Safari 7~15, but now it's separated.

Secondly, I don't know how multiple entries in BCD are sorted, but I naturally expects top to bottom as time goes.

**Comment by fiji-flo** [comment] 2022-03-04 19:39
I've been digging into this. Bringing back the old BCD tables triggers a lot of issues. We do plan to solve this in the future and make BCD tables better then ever.

I personally agree 100% that the old design was better then the new one, but let's figure out how to move forward. I have a proposal for a small change as an interim fix. There's two things I focused on. Bring back the version numbers as there's many reasons developers wanna see them like, ESR, and the fact that a lot of us have to support >3 versions and not just the release that landed yesterday. The other thing I wanted to finally solve is make it more accessible to people with various degrees of colorblindness, that's why the ✔️ and ❌ are icons are still in there along side the version numbers. I plan to hide it behind a toggle for now waiting for feedback and potentially use it as default and remove the toggle.

That being said, we do plan to really improve and fix BCD substantially but we wanna get it right and get some feedback while figuring it out so this is just an interim solution.

![image](https://user-images.githubusercontent.com/3604775/156827884-687e3a65-f351-4273-bdff-18d70e318f25.png)

**Comment by MichaelAllenWarner** [comment] 2022-03-04 21:39
@fiji-flo 

I certainly think that that would be an improvement over the new version-less table.

That said, the old table _also_ had asterisks and clickable-arrowheads that would let you know if a given cell came with additional information that a developer might need to know about (e.g., about partial support). Without those indicators, the (diligent) developer _still_ will have to click on each and every box in a row to rule out "more-important-information" scenarios before confidently using the feature in question.

I'm curious: were there complaints about the old table? I ask because this strikes me as a case of trying to fix something that wasn't broken. I love the idea of tweaking the colors to improve accessibility, but of course that could have been done without removing all (or any) of the useful at-a-glance information.

Thanks for digging into this so quickly, by the way.

**Comment by nschulzke** [comment] 2022-03-04 22:17
@fiji-flo, something to keep in mind with this whole redesign project is that these docs are for a demographic for whom function is *infinitely* more important than form. Most of us use CLI apps on a regular basis. If you look at pretty much every popular developer tool, you'll see that information density in particular is *extremely* high as compared to more consumer-grade applications. With that in mind, the direction this redesign has taken runs entirely contrary to the actual goals of developers.

Focusing on my personal usage of this specific table: **I would often spend all of a half second looking at it before making a decision.** All green? Go for it. All green except IE? Go for it. All green except that Firefox has an asterisk? Let's check that asterisk. The old design wasn't "pretty" by modern standards, but it was *exceptionally* well-planned for that workflow.

The fact that the full box was colored in allowed identifying incompatibilities at the speed of thought. No need to scan the table and check all the icons, if there was red, you *knew* it. The asterisk, the "show more" arrow, and the red X were huge and obvious. They immediately drew the eye because they were the only icons present in the table. In the new version, the color is isolated to the text and icons themselves, and all these check boxes distract from what I actually want to know. I'm not interested in which browsers *do* support it, I'm interested in how many *don't*.

With the old version, when I found an incompatibility, I could scan right up to the top and instantly recognize the browser by its icon. Now I have to read *sideways text* to figure out which browser is incompatible.

As for accessibility, the old design seems to have been plenty accessible. Taking a screenshot from earlier in the thread and running it through [color-blindness.com's simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/), I can immediately pick out all the important details in *every single mode*. Even when in full monochrome (attached below), the only thing I might say is you could probably increase the contrast on the X.

The new table is prettier, I'll give you that. But MDN is a tool used by working developers on a daily basis. A stepladder doesn't need to be pretty, a hammer doesn't need to be pretty, a set of pliers don't need to be pretty. They need to save us time. In some cases pretty is the enemy of useful, and when that is the case, a tool should *always* choose to be useful. Please, as you work on redesigning the redesign, make it *functional*, not pretty.

![canvas](https://user-images.githubusercontent.com/2680092/156848103-bf9ec32e-781c-4be1-bd55-927d03bdfb24.png)

**Comment by debiru** [comment] 2022-03-04 23:26
A change in design can lead to dissatisfaction from two perspectives.

One is that it is absolutely inconvenient. The other is that it is relatively inconvenient. The latter, in other words it is a matter of accustomedness. In the past, when the MacBook keyboard design was changed, there were also complaints. However, it is now accepted.

Is your dissatisfaction with this design change a matter of accustomedness? I don't think so. So what went wrong? We need to think about that carefully.

What I am trying to say is that even a new design table with a clearly marked version may be complained about at first. But I think that is a matter of accustomedness. I look forward to improvements in essential areas.

**Comment by ddbeck** [comment] 2022-03-08 17:43
Hey folks, I just wanted to reiterate that we're appreciative that you've all come here to share your concerns and offer suggestions. It would be much harder to fix these issues without your help.

To provide some additional background, we redesigned the compat tables to address some known issues with the former design. We had evidence that some readers were misunderstanding the former tables (e.g., not recognizing version number as version numbers, wrongly inferring other meanings) or ignored the numbers outright. Some of that evidence was direct (i.e., observed in usability testing and reader interviews) and indirect (e.g., bug reports for valid, confirmed compat data).

That evidence led us to overcorrect in the new design. It has inconvenienced a lot of you in the process. We're sorry about that. We're planning to ship some incremental improvements to the design this week (perhaps as early as tomorrow).

But we're not going to stop there. Now that we have a better idea of how readers are using the compat tables, we're going to take another look at how the whole page—not just the tables—can support MDN readers in understanding compatibility. That work is going to require a lengthier research, design, and implementation process, but this time it'll be based on a more complete and accurate picture of how you're using MDN.

**Comment by caugner** [comment] 2022-04-06 12:30
FWIW The version numbers have been restored via #5477 (shortly after the redesign), so I will go ahead and close this issue. 🎉 

> I don't know how multiple entries in BCD are sorted, but I naturally expects top to bottom as time goes.

@yume-chan FYI BCD history is now sorted chronologically (resolved via #5649).

> the old table _also_ had asterisks and clickable-arrowheads that would let you know if a given cell came with additional information that a developer might need to know (e.g., about partial support).

@MichaelAllenWarner FYI Symbols for notes, alternative names and prefixes have been restored. Kudos to @danielhjacobs for working on this.

> My concern is that the current implementations is very inaccessible and that resolving it might also have design implications. Choosing the right patterns for accessibility first will prevent another re-design later :)

@romainmenke FYI We have addressed one accessibility issue regarding a duplicate focus point in the feature cells via #5648, and #5710 will address some remaining accessibility issues with the website in general.

If you find any remaining accessibility issue with the BCD tables specifically, please don't hesitate to open a new issue for this. 🙏

**Closed by caugner** 2022-04-06 12:30 UTC
Labels: redesign, browser-compat
