### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch 

### ISSUE THREAD

**Issue by shivarajnaidu** [mdn/yari#1699] opened 2020-11-11 05:11 UTC
Getting Following error when i run the `yarn dev`

![image](https://user-images.githubusercontent.com/12374494/98771421-6f450800-240a-11eb-9db7-268e9e93f1a4.png)

**Comment by peterbe** [comment] 2020-11-11 12:07
@shivarajnaidu There is a way to increase the system limit and we plan to explain/mention it in the README. 

@fiji-flo Do you think it would be possible to trigger something like this:
```
try {
  startWatcher();
} catch(err) {
  if (err.toString().include("System limit for number of file watchers reached") {
    console.log("See this Troubleshooting tip about this error....")
  }
  throw err;
}
```

**Comment by Ryuno-Ki** [comment] 2020-11-11 22:04
Duplicate of #835

**Comment by peterbe** [comment] 2021-02-12 21:54
We don't use the watcher anymore for content. But you can still run into this error in Linux because of all the various source code files that `react-scripts` might be keeping an eye on. So we kept a blurb about it in the "Troubleshooting" section.

**Closed by peterbe** 2021-02-12 21:54 UTC
