### ISSUE TITLE
Navbar on  page with id=sidebar-quicklinks  and class = sidebar needs css update.

### ISSUE THREAD

**Issue by GittRabin** [mdn/yari#5031] opened 2021-12-04 01:26 UTC
Long text is overflowing. Word break might help word-break: break-word;

![image](https://user-images.githubusercontent.com/32501798/144691650-c5ff06f1-18b6-40ec-854e-4ce9c7fb1184.png)

**Comment by wbamberg** [comment] 2022-01-12 00:59
Duplicate of https://github.com/mdn/yari/issues/4973.

**Closed by wbamberg** 2022-01-12 00:59 UTC
Labels: needs-triage
