### ISSUE TITLE
Link styling and color choice in MDN docs redesign

### ISSUE THREAD

**Issue by ferdnyc** [mdn/yari#5854] opened 2022-03-30 07:03 UTC
Since my half-assed tweet was linked (in #5546) as "community feedback", I figured I'd open a more formal (or "fully-assed", if you prefer) report for inclusion into the mix there.

Basically, it boiled down to two things:

1. In the "Web APIs" section, the selected accent color (which is most relevant to this report  because it's used to set the text color for all links in the content) is very nearly the browser's default `a:visited` color. This makes the pages in that section appear to contain vast seas of already-visited links, which may be disconcerting to anyone for whom that color has particular meaning.<sup>1</sup>

2. Every time someone creates a site design like this:
   ```css
   a { color: var(--some-color-for-our-links); }
   a:visited { color: var(--some-color-for-our-links); }
   ```
  
   ...A puppy contracts canine leukemia.

   Visited-link coloring is still considered a useful navigation aid by some users. Unfortunately, styling it out of existence has become an epidemic among web designers.

   While opinions vary greatly regarding whether, and when, it's appropriate to style visited and unvisited links identically, let's just agree that it's a controversial practice. There are no clear guidelines or absolute criteria governing when and where to do so.

   ...As such, MDN's own design is not setting a stellar example by heavy-handedly applying it sitewide.

#### Notes
1. That's right, all 14 of us.

**Comment by schalkneethling** [comment] 2022-03-31 20:54
Hey @ferdnyc

Thank you for taking the time to open the issue and provide further details regarding this specific issue. I would ask that you read over our community guidelines [here](https://github.com/mdn/yari/blob/main/CODE_OF_CONDUCT.md) to understand the guidelines we use to ensure a healthy community. I bring this up because some of the language used in your description does not meet our guidelines.

I understand that you feel strongly about this topic, but please take a moment to reconsider your language use and update your description. Thank you for being part of the MDN Web Docs community and participating in our discussions.

**Comment by caugner** [comment] 2022-09-14 16:24
Duplicate of https://github.com/mdn/yari/issues/5755, has been resolved by https://github.com/mdn/yari/pull/5710.

**Closed by caugner** 2022-09-14 16:24 UTC
Labels: 🐌 idle, needs-triage
