### ISSUE TITLE
Set Introduction, Tutorial and Reference sections for CSS and HTML onto card grids again

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1741] opened 2020-11-13 18:46 UTC
The CSS Introduction, CSS Tutorials, CSS Reference, HTML Introduction, HTML Tutorials and HTML Reference sections were more eye catching when displayed onto card grids. 
![image](https://user-images.githubusercontent.com/53306802/99109180-14b9d080-25f1-11eb-926c-35d7acdaff01.png)

Currently they are not organized as such. For example:
https://developer.allizom.org/en-US/docs/Web/HTML
https://developer.allizom.org/en-US/docs/Web/CSS
![image](https://user-images.githubusercontent.com/53306802/99109268-387d1680-25f1-11eb-9154-1a6c43f9e0aa.png)

**Comment by peterbe** [comment] 2020-11-16 13:44
Duplicate of https://github.com/mdn/yari/issues/1742 but let's keep this open just a little longer so we don't forget about other pages that are affected by decisions and implications we make over there in that issue.

**Closed** 2020-11-16 17:19 UTC
