### ISSUE TITLE
Feature removals in BCD use a misleading version range

### ISSUE THREAD

**Issue by foolip** [mdn/yari#3971] opened 2021-06-04 10:10 UTC
I was sure I'd already filed an issue for this, but maybe it was for the old MDN site...

Take a look at this table:
https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/replacesClientId#browser_compatibility

The data for Edge being rendered here is:
```
"edge": {
  "version_added": "18",
  "version_removed": "79"
},
```

This is rendered as "18 — 79" on a red background. I think the natural interpretation of this that the feature was in versions 18-79, but the correct interpretation is that it was in Edge 18 only.

I think the logic here should be:
- The displayed end range is the version *before* `version_removed` in BCD.
- If that is the same as the start range, show just a single number on red, "18" in this case.

cc @Elchi3 @ddbeck

**Comment by foolip** [comment] 2021-06-04 10:15
While in the area, I'll also the the chance to complain about the use of the wide em dashes (&mdash;) here. The narrow en dash (&ndash;) is more commonly used to represent ranges.

**Comment by teoli2003** [comment] 2021-06-04 10:18
@foolip Is 79 a typo, and you meant 19 ?

**Comment by foolip** [comment] 2021-06-04 10:18
@teoli2003 no, this is a case of something that was in Edge 18 and then removed in Edge 79, which is the case where the problem is the most obvious.

**Comment by teoli2003** [comment] 2021-06-04 10:20
Oh yes, my bad, I understand now. Makes sense!

**Comment by caugner** [comment] 2022-11-15 21:08
Duplicate of https://github.com/mdn/yari/issues/3971.

**Closed by caugner** 2022-11-15 21:08 UTC
Labels: 🐌 idle
