### ISSUE TITLE
Next and Prev anchors layout

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1957] opened 2020-12-05 13:33 UTC
5 things:

- These 3 `a` should be inline
- These 3 `a` should be `2`, just _Prev_ and _Next_ inline
- I'm expecting that the `a` in centre is the current page, what is It?
- I don't know where to put the `a` in the center
- I think that if in at the beginning of the page i want to first of all read and then go to the Next Page

![Screenshot_20201205-142554.png](https://user-images.githubusercontent.com/44380480/101244319-12d1c180-3706-11eb-9cda-d6c8e1f9cd69.png)

![Screenshot_20201211-205156.png](https://user-images.githubusercontent.com/44380480/101948668-bc2b2280-3bf2-11eb-99ac-65ee626d3d81.png)

![Screenshot_20201211-205311.png](https://user-images.githubusercontent.com/44380480/101948775-e67ce000-3bf2-11eb-9673-88f31d49e949.png)

**Comment by schalkneethling** [comment] 2020-12-12 15:21
Duplicate of https://github.com/mdn/yari/issues/2089

**Closed by schalkneethling** 2020-12-12 15:21 UTC

**Comment by mattiapontonio** [comment] 2020-12-12 15:31
Remove the center button between previous and after
