### ISSUE TITLE
move form#lang in footer

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2045] opened 2020-12-09 22:53 UTC
![Screenshot_20201209-235235.png](https://user-images.githubusercontent.com/44380480/101698403-b231e400-3a79-11eb-9b38-ef22f32f65b4.png)

**Comment by schalkneethling** [comment] 2020-12-14 07:03
Duplicate of https://github.com/mdn/yari/issues/1486

**Closed by schalkneethling** 2020-12-14 07:03 UTC
