### ISSUE TITLE
YT Videos are rendered really small on MDN

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#2345] opened 2021-01-05 17:54 UTC
For example, see the video in this section:

https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations#Animation_inspector

**Comment by peterbe** [comment] 2021-01-06 13:43
Dupe of https://github.com/mdn/yari/issues/2245

**Closed by peterbe** 2021-01-06 13:43 UTC
