### ISSUE TITLE
Gap between page's start and header.

### ISSUE THREAD

**Issue by kutsen-rom** [mdn/yari#9040] opened 2023-06-08 08:26 UTC
### Summary

There's a gap between the start of the page and the header, so the content under header is seen through this gap

### URL

Basically most (or any) mdn page
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

### Reproduction steps

1. Open https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
2. Scroll down a bit so the content is under the top of the page

![gap](https://github.com/mdn/yari/assets/62949847/7dbd87ff-d448-47b8-beb0-36982c28e3b8)

![gap-highlight](https://github.com/mdn/yari/assets/62949847/a6ddfa7d-35a7-4d97-9693-31e3b310c5bb)

### Expected behavior

There should be no gap 

![should-be](https://github.com/mdn/yari/assets/62949847/4d407bc2-e9a4-474b-99ef-9db818c8b3cd)

### Actual behavior

There is a gap 
![gap](https://github.com/mdn/yari/assets/62949847/e534c1cf-d9db-4d56-a6e9-df49c070c4c2)
![gap-highlight](https://github.com/mdn/yari/assets/62949847/79209473-903a-4819-9dbb-f877086f2acb)

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![gap](https://github.com/mdn/yari/assets/62949847/128ef2df-7811-4543-bd3d-652b91846377)
![gap-highlight](https://github.com/mdn/yari/assets/62949847/9808ee07-f047-4833-b96b-4aad7ad9246c)

### Anything else?

I think I've found the way to fix it but I'm not sure if it is good enough.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [x] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment] 2023-10-02 11:14
Duplicate of https://github.com/mdn/yari/issues/9159.

**Comment by kutsen-rom** [comment] 2023-10-04 11:11
well mine was opened on 8th June, and the #9159 on 26th June, how it's a duplicate idk

**Comment by kutsen-rom** [comment] 2023-10-04 11:11
well mine was opened on 8th June, and the https://github.com/mdn/yari/issues/9159 on 26th June, how it's a duplicate idk

**Comment by caugner** [comment] 2023-10-04 16:28
Duplication is a symmetric relationship, so both issues are duplicates to each other, as they refer to the same issue.

https://github.com/mdn/yari/issues/9159 has more context, so we're keeping that one open.

Thank you for your understanding. 🙏

**Closed by caugner** 2023-10-04 16:29 UTC
Labels: needs triage, closed: duplicate
