### ISSUE TITLE
/es/docs/Web/Events/statechange -- Missing Page

### ISSUE THREAD

**Issue by AriBussi** [mdn/yari#2713] opened 2021-01-27 10:58 UTC
Normally, when a page is missing in Spanish I get this message:

![image](https://user-images.githubusercontent.com/56850922/105981510-7210da00-6096-11eb-9a51-5fb23ef28abf.png)

This is not the case for [](https://developer.mozilla.org/es/docs/Web/Events/statechange)

![image](https://user-images.githubusercontent.com/56850922/105981322-3d048780-6096-11eb-9a10-03fcb09d17fa.png)

If I change /es/ for /en/ I get to the desired page with its content in English, but for users that do not realize that, content will appear to be missing.

**Comment by peterbe** [comment] 2021-01-27 19:46
It's actually a duplicate of https://github.com/mdn/yari/issues/2528
But thanks for filing! We can use this to assert that a fix solved it.

**Comment by caugner** [comment] 2022-11-29 23:28
> Normally, when a page is missing in Spanish I get this message:
> (Screenshot of https://developer.mozilla.org/es/docs/Web/API/AudioNodeOptions)
> This is not the case for
> (Screenshot of https://developer.mozilla.org/es/docs/Web/Events/statechange)

This was most likely fixed by https://github.com/mdn/yari/pull/5630:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/495429/204670811-f152b347-bf94-4c5d-a1fb-bae285a52ef4.png">

**Closed by caugner** 2022-11-29 23:28 UTC
Labels: 🐌 idle
