### ISSUE TITLE
Red color too similar to generic missing link color

### ISSUE THREAD

**Issue by blueYOSHI9000** [mdn/yari#5703] opened 2022-03-21 17:21 UTC
### Summary

All links look like they're missing when the primary color is red. This is especially an issue because on the old site missing links were common and they used nearly the exact same color, but now that color is used for every single link.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

### Reproduction steps

1. Visit a site on MDN that uses red/orange as the primary color.
2. Look at any link.

### Expected behavior

Links not using a color associated with "missing links" as the default.

### Actual behavior

Every single link uses the color associated with "missing links".

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![](https://i.imgur.com/YkRB6RL.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment] 2022-09-14 16:21
Duplicate of https://github.com/mdn/yari/issues/5755, has been resolved by https://github.com/mdn/yari/pull/5710.

**Closed by caugner** 2022-09-14 16:21 UTC
Labels: 🐛 bug, 🐌 idle, needs-triage
