### ISSUE TITLE
Lack of Browser version in compatibility table is a major regression in usability

### ISSUE THREAD

**Issue by twig-atl** [mdn/yari#5497] opened 2022-03-07 01:15 UTC
# Summary

The old design quickly let us skim what browser version we can target when viewing an API.

## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale#browser_compatibility

## What is the problem?

I was stung by this when removing an API and missed that Safari 13 didn't have Intl.Locale because its collapsed by default in the new design but shows the tick of approval.

## What did you expect to happen?

See the first browser version which implemented the API: http://web.archive.org/web/20201004194354/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale

## Steps to reproduce the issue

View the links shown.

![image](https://user-images.githubusercontent.com/61523379/156951672-edc55372-3553-4bb0-bb5a-18e6d06ef2e0.png)

![image](https://user-images.githubusercontent.com/61523379/156951678-cf59af53-b9b2-4991-baa7-3a997c7887d4.png)

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: (what version?)
- [x] Firefox: (what version?)
- [x] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: (what version?)
- [x] Mac OS: (what version?)
- [x] Linux: (what distribution / version?)

**Comment by schalkneethling** [comment] 2022-03-07 09:13
thank you for reporting @twig-atl. The discussion and work related to this are being tracked in https://github.com/mdn/yari/issues/5366. I will therefore close this one as a duplicate of #5366

**Closed by schalkneethling** 2022-03-07 09:13 UTC
Labels: needs-triage, browser-compat
