### ISSUE TITLE
Code wrapping on mobile device (6-inch e-reader screen)

### ISSUE THREAD

**Issue by Den0702** [mdn/yari#5661] opened 2022-03-17 20:23 UTC
Hello everyone!

I want to emphasize and to narrow down to the main problem I have described among others in a more general previous issue I had opened. 
This problem is _code wrapping_
I would like to show you the image in which it can be seen that the code area is starting to become a mess, indentations are violated. 
The code is like being torn when exploring different examples from mdn on such a device. (Maybe) the code wrapping is better for bigger screens, like desktops, but here, as for me, it is a very big problem.

![20220306_125533](https://user-images.githubusercontent.com/30319035/156922138-f6c2d476-3109-4635-a6fa-bbc345e0af3b.jpg)

Kind regards,
Denis
_Originally posted by @Den0702 in https://github.com/mdn/yari/issues/5357#issuecomment-1059949594_

**Comment by caugner** [comment] 2022-03-18 11:32
Hi @Den0702, please use our [Bug report template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) when reporting new issues.

This issue is already tracked in #5357, but unfortunately it's not a priority right now.

Duplicate of #5357

**Closed** 2022-03-18 11:32 UTC
Labels: needs-triage
