### ISSUE TITLE
Issue with "Send feedback about MDN Web Docs": Store selected language.

### ISSUE THREAD

**Issue by infacto** [mdn/yari#5461] opened 2022-03-04 09:26 UTC
Could you please store the selected language. I want to develop in english only. I don't want to change the language in my browser. It's only dev related stuff. The MDN page does not remember the selected language. And since the latest update of the website - btw. thanks for the dark mode. - there is no button to quickly change to english anymore. The page could simple store the value in localStorage.

![image](https://user-images.githubusercontent.com/60390085/156736100-acbd2825-b996-4904-89de-00121dcc0298.png)

**Comment by infacto** [comment] 2022-03-21 07:58
I see the `preferredlocale` set to `en-US` but it seems that the website does not care. Not sure if this sometimes works. But wait... It's maybe because Google search result link of MDN has the language in the URL. For example 

`https://developer.mozilla.org/{lang}/docs/...`

But in this case the website should ignore this and load `preferredlocale` from cookies. Because even if someone shares a link from MDN, the language in the URL doesn't matter if the user has selected a preferred language.

**Comment by schalkneethling** [comment] 2022-03-21 12:19
@infacto Indeed, if you follow a link that already has the locale as part of the URL, it will override the setting. [This PR](https://github.com/mdn/yari/pull/3968) would resolve this and is something we are considering finishing up and landing.

**Comment by caugner** [comment] 2022-10-25 16:36
Closing as duplicate of https://github.com/mdn/yari/issues/2724.

**Closed by caugner** 2022-10-25 16:36 UTC
Labels: localization, ux, 🐌 idle, needs-triage
