### ISSUE TITLE
Home/End keyboard buttons don't work in the search box

### ISSUE THREAD

**Issue by captainbrosset** [mdn/yari#10074] opened 2023-11-23 14:55 UTC
### Summary

The Home and End keyboard buttons don't work in the MDN search box. I rely on them quite frequently to select all text, by using the Shift modifier.

### URL

Any URL

### Reproduction steps

1. Go to any MDN page.
2. Focus the search field in the top right corner.
3. Type a few characters.
4. Hold Shift and press Home.

### Expected behavior

I expect the entire text to be selected, so I can start typing over.

### Actual behavior

Nothing happens.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment] 2023-11-23 15:22
Hi @captainbrosset,

It looks like the problem you're reporting is a duplicate of https://github.com/mdn/yari/issues/6466, and [our position](https://github.com/mdn/yari/issues/6466#issuecomment-1244487880) hasn't changed, so we recommend to use <kbd>Ctrl+LeftArrow</kbd> and <kbd>Ctrl+RightArrow</kbd> instead (combine with <kbd>Shift</kbd> to select).

Let us know if those alternatives don't work for you. 🙏

**Closed by caugner** 2023-11-23 15:22 UTC
Labels: needs triage
