### ISSUE TITLE
Issue with "Window.sessionStorage": The scroll of the page gets misaligned after the content tab reaches the end of its scroll at footer.

### ISSUE THREAD

**Issue by AbhiGhorai** [mdn/yari#5438] opened 2022-03-02 20:36 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

#### What information was incorrect, unhelpful, or incomplete? Information 

Even with a slight scroll of the central container, the left one scrolls massively. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/sessionstorage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/sessionstorage/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by caugner** [comment] 2022-03-03 19:05
Hi @AbhiGhorai, thanks for taking the time to report this. 👋 

Unfortunately I'm unable to reproduce the issue, so this might have been resolved by #5413.

Could you please verify if the problem persists?
If you still have it, would you be able to provide a screen recording, or the exact steps for us to reproduce?

\Thanks again!

**Comment by schalkneethling** [comment] 2022-04-19 17:39
It seems this is resolved so I am going to close the issue. Please feel free to re-open if the problem still exists.

**Closed by schalkneethling** 2022-04-19 17:39 UTC
Labels: 🧑‍🤝‍🧑 community, redesign, sidebar/toc
