### ISSUE TITLE
Update button isn't working

### ISSUE THREAD

**Issue by mshajid** [mdn/yari#8550] opened 2023-03-31 22:16 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

### What specific section or headline is this issue about?

The update button for Example is not working

### What information was incorrect, unhelpful, or incomplete?

According to the instructions, MDN has asked us to _press the update button to run the example repeatedly to see different random sets_. But I clicked it, and nothing changed, or maybe if doesn't change then make sure to give us a clear explanation that what should happen there. **confusing for beginners**. 

### What did you expect to see?

Since MDN has asked to press the button to see the random sets, but the button is not responsive, and the canvas is also the same.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#looping_code_example

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by mirunacurtean** [comment] 2023-04-03 10:04
@mshajid I have also tried to reproduce this on Chrome while logged with an MDN Plus account but I did not get the same issue. 
![image](https://user-images.githubusercontent.com/53306802/229467631-f1b1a6e1-0fb6-4bf4-bdd6-c483649dd239.png)

From what I see in the console that is a CSP error that I am not getting. 
Could you please try using a fresh Chrome profile and see if this is also happening there? 
What about on Firefox?

CC: @LeoMcA

**Comment by LeoMcA** [comment] 2023-04-03 11:13
I also can't reproduce (logged in/out, Firefox/Chromium), and I can't think of any way one's logged in state could modify the CSP headers.

@mshajid I see you've got a bunch of Chrome extensions installed, could you try without them (either disable, or try a fresh profile as @mirunacurtean suggests), and can you try logging back in to see if you can consistently get the error when logged in?

**Comment by mshajid** [comment] 2023-04-03 11:29
@mirunacurtean & @LeoMcA 

- Checked with a Guest account in browser - (_Working_)
- Checked with a Incognito mode and Other browsers as well - (_Working_)
- I logged out from the MDN Plus and Disabled the extensions - (_Working_).

**Comment by caugner** [comment] 2023-10-11 08:47
Unfortunately, we cannot reproduce this and we haven't received other reports about it, so I will go ahead and close this issue.

**Closed by caugner** 2023-10-11 08:47 UTC
Labels: 🐛 bug, interactive-examples, need more info
