### ISSUE TITLE
Make Browser Compatibility Clearer

### ISSUE THREAD

**Issue by tamtnguyen93** [mdn/yari#5475] opened 2022-03-04 00:08 UTC
I recommend a change to the compatibility table to make it's clearer; especially, grid and flex layout.  For example, Align Items, the Start and End rows in the table with different data, because of that, it really confusing to tell which is for flex or grid layout.

**Comment by danielhjacobs** [comment] 2022-03-10 19:46
Seems to be a duplicate of https://github.com/mdn/yari/issues/3321? That issue has been marked idle though.

**Comment by ddbeck** [comment] 2022-03-11 12:57
Yes, this is a duplicate of #3321. Closing in favor of that issue, since it's still valid. I'll leave a comment making that explicit, however. Thank you!

**Closed by ddbeck** 2022-03-11 12:57 UTC
Labels: redesign, browser-compat
