### ISSUE TITLE
Nss 3.36 version is not supporting EC keys

### ISSUE THREAD

**Issue by kalyank23** [mdn/yari#2838] opened 2021-02-05 22:22 UTC
Nss 3.36 version is not supporting EC ( Elliptic Curve) keys and is causing PKCS unknown error in RHEL6, could you please let us know if EC keys are supported by NSS or not?

EC keys will have starting string "-----BEGIN EC PRIVATE KEY-----"

While going through official website of NSS https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS, I came across here.

![image](https://user-images.githubusercontent.com/34736945/107095402-bfc3da00-682e-11eb-88fb-518793f2d1da.png)

**Comment by Ryuno-Ki** [comment] 2021-02-05 23:10
I suggest to close as duplicate of https://github.com/mdn/yari/issues/2837 and https://github.com/mdn/yari/issues/2802
Please stop.

**Comment by escattone** [comment] 2021-02-05 23:30
@kalyank23 To be clear, those links are not for reporting suspected bugs/issues with NSS, but rather for reporting issues with the documentation on MDN Web Docs (or the code that we use to build, deploy, and serve that documentation -- which we call the "platform"). You will need to ask your question directly to the team responsible for NSS. I think their repository is at https://hg.mozilla.org/projects/nss.

**Closed by escattone** 2021-02-05 23:30 UTC
