### ISSUE TITLE
Issue with "border-image-slice": demo border-image not always showing

### ISSUE THREAD

**Issue by jsnkuhn** [mdn/yari#5294] opened 2022-02-14 21:15 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice

#### What information was incorrect, unhelpful, or incomplete?
Sometimes on page reload the `border-image-source` for the first three examples does not load. It shows the fallback solid black border instead.

#### Specific section or headline?
CSS Demo: border-image-slice

#### Did you test this? If so, how?
not sure if a bug with page or a bug with FF. Using Firefox 97. 
![GIF](https://user-images.githubusercontent.com/1286791/153947216-a3e1ccf3-592c-477a-aaa8-b9252977b5e5.gif)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/border-image-slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/border-image-slice/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by caugner** [comment] 2022-09-15 17:42
Unfortunately, I cannot reproduce the issue, and since it hasn't gotten any upvotes, I'm closing it as "can't repro".

@jsnkuhn If you still experience this issue, please have a look at the "Network" panel in the Firefox DevTools, and let us know why the GET request to https://interactive-examples.mdn.mozilla.net/media/examples/border-diamonds.png fails (and what referer that request had).

PS: I did notice that the image is loaded twice, once because it's referenced both [as an interactive example](https://interactive-examples.mdn.mozilla.net/live-examples/css-examples/backgrounds-and-borders/border-image.css) ([Try it](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice#try_it) section) and [as a live sample](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/CSS/border-image-slice/_sample_.adjustable_border_width_and_slice.html) ([Examples](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice#adjustable_border_width_and_slice) section), but that shouldn't _really_ cause an issue.

**Closed by caugner** 2022-09-15 17:42 UTC
Labels: 🐌 idle, needs-triage

**Comment by jsnkuhn** [comment] 2022-09-15 21:36
Went back to give this another try and now I can't get it to break either (which is good... I... guess). Possible, i guess, that between FF97 and 104.0.2 there was a bug fix relate to `border-image`. No idea. Non the less, thanks for taking the time to look into it.
