### ISSUE TITLE
Window API articles that exist in production site but have no source in mdn/content

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2690] opened 2021-01-26 03:22 UTC
The following two articles exist on the production site:

* https://developer.mozilla.org/en-US/docs/Web/API/Window/clipboardchange_event
* https://developer.mozilla.org/en-US/docs/Web/API/Window/getAttention

…but no source for those exists in the mdn/content repo:

  https://github.com/mdn/content/tree/main/files/en-us/web/api/window/

So I’m wondering where the source for those comes from.

**Comment by peterbe** [comment] 2021-01-26 13:28
It's probably because we don't have a way to delete built pages. 
In a sense, this issue is a dupe of https://github.com/mdn/yari/issues/2224 but let's keep it open and when @escattone has implemented the new functionality, we can use this issue to confirm that it worked.

**Comment by peterbe** [comment] 2021-01-26 13:35
Based on https://s3.console.aws.amazon.com/s3/buckets/mdn-content-prod?region=us-west-2&prefix=main/en-us/docs/web/api/window/&showversions=false I can see that the last time it built was Jan 13. 
Then, on this folder history page https://github.com/mdn/content/commits/main/files/en-us/web/api/window you find:
* https://github.com/mdn/content/commit/e195da60b8037c13ded385ef66f94a038f04b55f#diff-7f34f5b263dae8be6ec63710d4d57cd1d1243b5bf59d4d5339a28194e71e30e1
* https://github.com/mdn/content/commit/8231b5cbdfa148f5c23819d3448b4ce535785923#diff-7f34f5b263dae8be6ec63710d4d57cd1d1243b5bf59d4d5339a28194e71e30e1

Which makes sense. Yeah, we clearly need to fix that deployer thing that deletes un-built stuff.

**Comment by peterbe** [comment] 2021-02-12 21:06
Blocked on https://github.com/mdn/yari/issues/2224 
Hint hint @escattone

**Comment by mattiapontonio** [comment] 2021-02-15 00:12
FTR
https://github.com/mdn/content/commits/main?before=0c6578a2e1479a5cd2ded2889afc4cb76e0c62c4+35&branch=main&path%5B%5D=files&path%5B%5D=en-us&path%5B%5D=web&path%5B%5D=api&path%5B%5D=window

- How to search in Git [deleted](https://intellipaat.com/community/9088/git-how-to-find-a-deleted-file-in-the-project-commit-history) files?
- How to [list files deleted](https://stackoverflow.com/a/6018043/3579536) between 2 commits on main? Those files should _redirect_ to 410?

**Comment by schalkneethling** [comment] 2021-11-03 12:46
@escattone are we good here now?

**Comment by escattone** [comment] 2021-11-03 20:41
@schalkneethling Yes, we're all good here now, thanks!

**Closed** 2021-11-03 20:41 UTC
