### ISSUE TITLE
illegibile layout for interactive example

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2363] opened 2020-12-09 22:44 UTC
# `portrait` screenshot 👎
![Screenshot_20201209-234257.png](https://user-images.githubusercontent.com/44380480/101697623-721e3180-3a78-11eb-8542-8bcab1562563.png)

Sample URL
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

# `landscape` screenshot 🤏 (pretty usable)
![Screenshot_20210107-143152.png](https://user-images.githubusercontent.com/44380480/103898401-28ffe280-50f5-11eb-8c3f-f5f62cbf0e22.png)

**Comment by schalkneethling** [comment] 2021-01-07 13:18
@escattone what do you think, should we just hide the HTML interactive examples on anything smaller than a tablet device in landscape mode? I will double-check but I think the CSS and JS examples are still useable/useful on mobile

**Comment by mattiapontonio** [comment] 2021-01-07 14:19
Don't hide anything. I work practically only from mobile like the business man 💼

**Comment by escattone** [comment] 2021-01-07 22:53
@schalkneethling What do you think of moving the `Output` section of all interactive examples below the tabbed code section, **for all cases**, mobile (vertical or horizontal), tablet and desktop? It seems like a win/win. We're not trying to cram too much into the horizontal space (which hurts us on mobile devices), and it feels (at least to me) more natural to have the "Output" section below.

It seems that we already do that for the JavaScript examples (see below)?

###  Mobile (simulated using the `Responsive Design Mode`)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/3743693/103952535-6c5a5100-50f5-11eb-88bf-6f9e2be60f46.png">

### Desktop
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/3743693/103952619-96ac0e80-50f5-11eb-9234-f764f24de1d7.png">

It seems to me that would make the HTML interactive examples usable even when in the "vertical" mode on a mobile device.

**Comment by mattiapontonio** [comment] 2021-01-07 23:02
I like It. 
If You have a staging URL i can test and screeshot.

**Comment by schalkneethling** [comment] 2021-01-08 08:24
> What do you think of moving the `Output` section of all interactive examples below the tabbed code section, **for all cases**, mobile (vertical or horizontal), tablet and desktop?

That seems worth looking into. I will have a look at all the places this will impact and estimate the amount of work. Thank you for the feedback @escattone

**Comment by mattiapontonio** [comment] 2021-01-08 11:48
I still don't understand what the flow is if the issue impacts 2 repositories.

**Comment by schalkneethling** [comment] 2021-01-11 10:53
Turns out this is actually a duplicate of https://github.com/mdn/yari/issues/1720

**Closed by schalkneethling** 2021-01-11 10:53 UTC
Labels: enhancement, frontend, ux
