### ISSUE TITLE
Conversion of inline tags to Markdown

### ISSUE THREAD

**Issue by cw118** [mdn/yari#5074] opened 2021-12-14 18:18 UTC
A few errors that have been found related to the conversion of inline tags to Markdown:

- On several pages, when there are `<em>` and `<strong>` tags nested within another, it seems that the markdown converter is converting `<em>` to escaped asterisks (`\*`). 
  - For example, for text that should be rendered as _**bold text** nested in italics_, it gets converted to this markdown: `**\*bold text** nested in italics\*`, which renders incorrectly as: **\*bold text** nested in italics\*.
  - Examples of this were discussed in [mdn/content#11203](https://github.com/mdn/content/issues/11222).

- Another that appears quite often is backticks turning into an escape character: `<br>` (\`\<br>\` in markdown) is converted to:
`\<br>`, ultimately rendering the tag as regular text instead of in code format.

Not quite sure, but there may be more issues with other types of inline tags.

**Comment by PythonCoderAS** [comment] 2021-12-14 23:51
I think enforcing underscores for `<em>` tags and asterisks for `<strong>` tags will be the best way to do this since no escaping will need to be done. Also, to my knowledge, using triple asterisks is still valid, so a block such as `***This text will be italic and bolded** just italic*` should render as: ***This text will be italic and bolded** just italic*.

**Comment by PythonCoderAS** [comment] 2021-12-15 00:04
Ok, as shown in mdn/content#11222, the error is not just with `<em>`, but with any of the inline tags, such as backticks and probably even strikethrough.

**Comment by cw118** [comment] 2021-12-15 00:45
> Ok, as shown in [mdn/content#11222](https://github.com/mdn/content/issues/11222), the error is not just with `<em>`, but with any of the inline tags, such as backticks and probably even strikethrough.

Thanks for pointing that out! What I notice sometimes is that the placement of whitespace can mess with rendering (ie. 
This: _**Note:**Some text here..._ won't make **Note:** bold as it's meant to due to the lack of a space between the two closing asterisks and the word "Some"), so that might also be part of the issue with certain tags.

**Comment by schalkneethling** [comment] 2021-12-31 16:07
Duplicate of: https://github.com/mdn/yari/issues/4648

**Closed by schalkneethling** 2021-12-31 16:07 UTC
Labels: needs-triage
