### ISSUE TITLE
Versioning in BCT

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1925] opened 2020-12-03 18:55 UTC
There Is something strange in versioning in BCT.
I like how Node does.
`<=` Is not equal to _not supported_ or _deprecated_ so _red_?

https://docs.npmjs.com/about-semantic-versioning

![Screenshot_20201203-195105.png](https://user-images.githubusercontent.com/44380480/101074769-6e366f00-35a1-11eb-9d59-e7c55af62d5b.png)

**Comment by peterbe** [comment] 2020-12-04 12:29
There's a duplicate of this already. Do you think you can search and find it?
I guess what you're saying is that `≤37` means that it's not supported in version 38 and onwards, therefore it should be red. Is that what you mean?
Also, what does that have to do with semantic versioning? What's the connection?

**Comment by mattiapontonio** [comment] 2020-12-04 12:34
https://github.com/mdn/yari/issues/1607

Semantic versioning seem talks only about going _Up_ and not _Down_ so the past does not care but only the future does. 
At least block to something in time until some Bot do not PR for You.

**Comment by peterbe** [comment] 2020-12-04 15:22
Thanks for finding the dupe.

**Closed by peterbe** 2020-12-04 15:22 UTC
