### ISSUE TITLE
Exposed HTML element in page content 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1586] opened 2020-10-30 14:53 UTC
**Browsers:**
Firefox Release
Chrome

**Devices:**
Windows pro 10 64-bit
Android 9.0.0

**Steps to reproduce:**
1. View the following pages: 
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Feedback
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Community
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/About
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Contribute
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Contribute/Howto
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Contribute/Localize
https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Kuma

**Actual result:** 
The element is not rendered on the page in a way that provides a functionality. 
![image](https://user-images.githubusercontent.com/53306802/97719802-2fa82300-1ad0-11eb-8c18-ec39cf164b92.png)

**Comment by peterbe** [comment] 2020-10-30 20:58
Thank you! 
But duplicate of https://github.com/mdn/yari/issues/1041 
Clearly it's happening on quite a few pages.

**Closed by peterbe** 2020-10-30 20:58 UTC
