### ISSUE TITLE
handler.construct() Try it Error

### ISSUE THREAD

**Issue by cohenerickson** [mdn/yari#6081] opened 2022-04-26 19:30 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/construct

### What specific section or headline is this issue about?

Try It

### What information was incorrect, unhelpful, or incomplete?

502 Error

### What did you expect to see?

Try it container

### Do you have any supporting links, references, or citations?

![image](https://user-images.githubusercontent.com/72945444/165377554-708af105-ae1d-407a-8f1f-0a4fc3da81c3.png)

**Comment by schalkneethling** [comment] 2022-04-26 22:03
Closing as a duplicate of https://github.com/mdn/yari/issues/6079. Thank you for reporting @cohenerickson

**Closed by schalkneethling** 2022-04-26 22:03 UTC
Labels: 🧑‍🤝‍🧑 community, needs-triage
