### ISSUE TITLE
Allow sidebar to be collapsable on larger viewports

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5976] opened 2022-04-13 20:47 UTC
While working on the readability project, I got feedback from several people concerning the sidebar on larger viewports. On mobile, the sidebar is collapsed offscreen and can be shown via an expand button. While we probably do not want it collapsed by default on larger viewports, we could consider making the functionality available to readers.

I think viewports of `1366px` and smaller should be considered.

**Comment by caugner** [comment] 2022-09-13 17:36
Duplicate of #5975.

**Closed by caugner** 2022-09-13 17:36 UTC
Labels: 🌱 feature-request, 🐌 idle, needs-triage
