### ISSUE TITLE
(Ru) The table on 'Guide/Regular_expressions' page is cropped

### ISSUE THREAD

**Issue by bsmth** [mdn/yari#9891] opened 2023-10-26 15:08 UTC
### Summary

The table content extends beyond the center column max-width on this article

### URL

[JS Regex Guide](https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Regular_expressions#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2)

### Screenshots

![image](https://github.com/mdn/yari/assets/43580235/e57461bf-d4cf-427f-978b-2b3f0ba86ccd)

### Discussed in https://github.com/mdn/yari/discussions/9890

<div type='discussions-op-text'>

<sup>Originally posted by **Mrpancho92** October 23, 2023</sup>
https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Regular_expressions

If you substitute the value: max-width: 680px in the <td> tag, then everything is ok</div>

**Comment by caugner** [comment] 2023-10-30 09:25
@bsmth @Mrpancho92 Generally it is the intended behavior that wide tables scroll vertically.

The reason for the overflowing table is this long inline code block for `\S`, that doesn't allow the user to insert any soft line break:

```
[\f\n\r\t\v\u00A0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u2028\u2029\u202f\u205f\u3000]
```

This two-column table looks a lot like a definition list and could possibly be refactored accordingly.

Otherwise the character class could be shortened by replacing `\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a` with `\u2000-\u200a`, which will allow the browser to add a line-break at the `-` as a side-effect (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Character_classes#types).

From the perspective of yari, I will go ahead and close this issue as "won't fix".

**Closed by caugner** 2023-10-30 09:25 UTC
Labels: ux, needs triage
