### ISSUE TITLE
Code snippets have too much line-height

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1490] opened 2020-10-20 00:28 UTC
I don't know why but the monospace font code examples just appear to have too much line-height. 

In Fiori:
<img width="383" alt="current-fiori" src="https://user-images.githubusercontent.com/26739/96525550-3c638600-1249-11eb-9011-0ca8accb430c.png">
Its `line-height` in inherited from the `body` and its value is `1.6`. 

If I change it to `1.4` just using the devtools it looks like this:
<img width="407" alt="1 4" src="https://user-images.githubusercontent.com/26739/96525600-5bfaae80-1249-11eb-98cc-7782efa7b2f3.png">

I know I'm an old hat but it's just something odd about code looking like long-form prose. 
Perhaps it's just me, in that case, close it. But it's an undeniable impression that it's odd to see code displayed as if it was free-flowing text.

**Comment by peterbe** [comment] 2020-10-20 00:29
Sample page I was looking at https://mdn-fiori.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/closures

**Comment by jess-cook03** [comment] 2020-10-20 00:50
@peterbe 
My first thoughts are ...... 👀 (me looking again and then again to see the changes between the images lol)
This is very subtle to me... I almost see no difference between the two....
That being said I am not the target audience that is looking at code 24/7 so this isn't something that I would typically notice.

I think that these code block components should ideally represent what code truly looks like (and maybe feels like, to developers?)... 
Having it inherit the body line spacing makes sense to me from a systemic design perspective to keep the overall typographic rhythm down the page layout.... but I could see a case being made for giving the code block components their own unique line spacing to account for the different font and desire to look as close to real code as possible....?

Apologies since I don't have a strong opinion either way..... I could see it staying as is and being totally fine as well.

Hope that helps! (at least somewhat)

**Comment by chrisdavidmills** [comment] 2020-10-20 07:26
I think I agree with Peter here — the `line-height` should be a bit smaller, to make it feel more like a typical code editor.

Incidentally, my view in Atom looks like this:

![Screen Shot 2020-10-20 at 8 22 52 AM](https://user-images.githubusercontent.com/47647/96553801-98f88c80-12ad-11eb-8d07-5ad8b5c07b98.png)

I checked the preferences and it reckons the `line-height` for this is 1.5. But it does look significantly smaller than the first image you included above. Shall we try 1.4 for now, and see if we get any feedback on it?

**Comment by schalkneethling** [comment] 2020-10-20 07:53
Hey All,

Thanks for filing @peterbe. The way it is now is not final and will be addressed as part of https://github.com/mdn/yari/issues/1136

**Comment by schalkneethling** [comment] 2020-10-20 07:54
Closing as a duplicate of https://github.com/mdn/yari/issues/1136 - Thanks for the feedback @chrisdavidmills @jess-cook03 @peterbe 🌮

**Closed by schalkneethling** 2020-10-20 07:54 UTC
