### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1805] opened 2020-11-21 08:06 UTC
I can't find the issue where I myself reported that the page title was causing an overflow. Now the title is broken on any letter which is good when the page title is very long and it is a single word. However, if the title is a simple sentence that could normally be broken between words, this way of breaking the line is inelegant. At the moment I am not reminded of the CSS solution for this problem but I think I remember that there is a way to set both behaviors.

I don't know of a permanent solution for this problem. I have already investigated it in the past. An even better solution could be to go back to breaking the line as per default, definitely decrease the text but only on mobile (I don't know if leaving the text size unset this is expressed according to the device) and at most decay on the use of ellipsi as per link. I attach Wikipedia which evidently has the smaller font body which is more readable.

https://www.w3schools.com/cssref/css3_pr_text-overflow.asp

![Screenshot_20201121-133029](https://user-images.githubusercontent.com/44380480/99877436-85b74480-2bfe-11eb-9b4a-82ec0693686d.png)

**Comment by mattiapontonio** [comment] 2020-11-21 12:36
I don't know of a permanent solution for this problem. I have already investigated it in the past. An even better solution could be to go back to breaking the line as per default, definitely decrease the text but only on mobile (I don't know if leaving the text size unset this is expressed according to the device) and at most decay on the use of ellipsi as per link. I attach Wikipedia which evidently has the smaller font body which is more readable.

https://www.w3schools.com/cssref/css3_pr_text-overflow.asp

![Screenshot_20201121-133029](https://user-images.githubusercontent.com/44380480/99877436-85b74480-2bfe-11eb-9b4a-82ec0693686d.png)

**Comment by peterbe** [comment] 2020-12-02 20:42
Would you mind rewriting this issue so we can clearly understand what the problem is? Right now, it feels like distracting noise.

**Comment by mattiapontonio** [comment] 2020-12-03 08:48
![Screenshot_20201203-094639.png](https://user-images.githubusercontent.com/44380480/100985598-77e1b780-354c-11eb-91a4-96834d416454.png)

- Less `font-size` on `h1` on mobile (like Wikipedia)
- Break words with hypens

**Comment by peterbe** [comment] 2020-12-03 16:20
I too agree that the `<h1>` is much too large on mobile.

**Comment by mattiapontonio** [comment] 2020-12-03 16:26
I still not understand if You use `em` or `rem` (or keeps default font sizes) this problems is automatically solved 💭

**Comment by peterbe** [comment] 2020-12-03 19:03
You don't need to know. You just need to find the existing size definition. If it says 13em you change it to 12em. And if it says 13rem you change it to 12rem :)

**Comment by mattiapontonio** [comment] 2020-12-03 19:17
We need a emoji for benefit of the doubt 🤔

**Comment by peterbe** [comment] 2020-12-04 12:33
Yeah, I wouldn't mind if they were a bit smaller on mobile. It's for @schalkneethling to decide and perhaps something to look for in the future if/when we revisit the design.

**Comment by mattiapontonio** [comment] 2020-12-04 12:44
I thinking about use only `rem` and change `root` (`html`) `font-size` directly on mobile.
Is already like that?

**Comment by schalkneethling** [comment] 2020-12-07 17:05
The font sizing is based on a type scale so, if people feel that the size is too large, we need to revisit the scale on mobile. We should not just change for example the size of the `h1`. This is also all defined in minimalist so, the change will happen there.

This is the current scale:

```
/* Mobile typescale based on minor third typescale with a base of 
   100% of base font size set by the user. */
$xxl-font-size-mobile: 2.488rem;
$xl-font-size-mobile: 2.074rem;
$large-font-size-mobile: 1.728rem;
$medium-font-size-mobile: 1.44rem;
$small-medium-font-size-mobile: 1.2rem;
```

We can experiment with:

```
$xxl-font-size-mobile: 1.802rem;
$xl-font-size-mobile: 1.602rem;
$large-font-size-mobile: 1.424rem;
$medium-font-size-mobile: 1.266rem;
$small-medium-font-size-mobile: 1.125rem;
```

I will make the change and we can test and see how folks feel.

**Comment by mattiapontonio** [comment] 2020-12-07 18:27
There is some good in the default styles but you also have to consider how things look as they go. In some projects, for example, the measurements were always in pixels to have control over each text. The right BEM was also used to throw away the logic of CSS. You have to understand if you are lazy or if you want to work, I am lazy.

![Screenshot_20201207-192325.png](https://user-images.githubusercontent.com/44380480/101389626-01351900-38c2-11eb-8d98-fb52cccd24d3.png)

https://www.w3.org/TR/CSS2/sample.html

It's always a trade-off but so use pixel... So You don't have to deal with strange math... ✋

**Comment by schalkneethling** [comment] 2020-12-08 06:25
@mattiapontonio I respectfully disagree. Pixels forces a defined size on your users. Using a relative unit such as `rem` allows your user to set a base font size that they feel comfortable with and they increment the size of the headings based on that base font size.

This is the reason we changed to setting the base `font-size` on the `body` to `100%` as opposed to a fixed pixel size. This is also critical for accessibility.

**Comment by schalkneethling** [comment] 2020-12-08 08:53
The change has landed, please see below for the before and after:

### Before

![Screenshot of main title size before change](https://user-images.githubusercontent.com/10350960/101461437-8c0a2800-3943-11eb-8b71-280f56c76dec.png)

### After

![Screenshot of main title size after change](https://user-images.githubusercontent.com/10350960/101461448-8f9daf00-3943-11eb-9197-8a024604f046.png)

Closing this issue. Please feel free to reopen if people still feel the text is to large:

**Closed by schalkneethling** 2020-12-08 08:53 UTC
