### ISSUE TITLE
Issue with "How to structure a web form": …

### ISSUE THREAD

**Issue by nbbbrewer** [mdn/yari#2187] opened 2020-12-17 16:58 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

#### What information was incorrect, unhelpful, or incomplete?
This is a suggestion for an improvement. In the code block sections there is often overflow content which causes a horizontal scroll bar to appear at the bottom of the block. Would it be possible to make the code block sections wider? It would be easier to type the code if I didn't have to repeatedly scroll down and adjust the horizontal bar.

#### Specific section or headline?
Step 5 of '_Active learning: building a form structure_' is a good example of this. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/forms/how_to_structure_a_web_form/index.html
* Report started: 2020-12-17T16:16:43.657Z

</details>

**Comment by schalkneethling** [comment] 2020-12-18 13:04
@nbbbrewer Are you here referring to the in-browser "editor" offered by Yari, or how some of the code blocks are displayed?

**Comment by nbbbrewer** [comment] 2020-12-18 19:01
@schalkneethling How the code blocks are displayed.

**Comment by peterbe** [comment] 2021-01-05 17:07
The `<pre>` tags within the `<ol><li>` are much too narrow.
<img width="767" alt="Screen Shot 2021-01-05 at 12 06 59 PM" src="https://user-images.githubusercontent.com/26739/103675960-86a5fa80-4f4e-11eb-8bf1-d3f51c2aa424.png">

Compared to the `<pre>` tags above:
<img width="1259" alt="Screen Shot 2021-01-05 at 12 07 50 PM" src="https://user-images.githubusercontent.com/26739/103676071-a50bf600-4f4e-11eb-9c9b-b1840d08f0af.png">

**Comment by schalkneethling** [comment] 2021-01-11 15:36
This feels more like a content issue, and not an easy one at that. The problem is when these code blocks are used inside an ordered list, for example, the width of the list is affected by the `readable-line-length` class which sets to max-width to roughly 80 characters.

It is nice to have the steps marked up as an ordered list though. Perhaps we can use multiple lists and continue the number order using the `start` attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#attributes

@chrisdavidmills Thoughts?

While browser support is good for the attribute, I am not 100% on how this affects people using assistive technologies.

**Comment by mattiapontonio** [comment] 2021-01-11 16:15
Do You like formatting HTML like this?

```HTML
<tag
attribute-1="value-1"
attribute-2="value-2"
/>
```

That's render things vertical.
(Possibile discussion)

**Comment by chrisdavidmills** [comment] 2021-01-11 18:29
> @chrisdavidmills Thoughts?

This is a challenging one. I often try to insert line breaks in such examples to shorten the lines, but it isn't always easy to do that without making the code look weird, or introducing problems.

And I wouldn't want to use multiple lists with start attributes because that would be really screwy, accessibility-wise.

One thought sprang to mind — could we write some code to make it so that, when a code example has a horizontal scrollbar, the example is given a "View in separate tab" button that throws the content into a new tab, or even opens it into a modal window that stetches the full width of the screen? So for each step, you could open the model/new window, type the code in, and then close it again and go onto the next step?

**Comment by peterbe** [comment] 2021-01-12 14:30
> code example has a horizontal scrollbar, the example is given a "View in separate tab" button

Code examples don't live on their own. Unlike live samples which are static files stored in S3 and served via an `<iframe>`. 
Modals aren't bad. It's not a terrible idea. I like when you can click an image to see it much larger in a modal. 
But modals have their own set of flaws. 
Yari has a modal solution. We're currently only using it for the sign-in, but just yesterday we decided to drop that. I guess we can revive it if we have to :)

**Comment by schalkneethling** [comment] 2021-01-12 14:45
> One thought sprang to mind — could we write some code to make it so that, when a code example has a horizontal scrollbar, the example is given a "View in separate tab" button that throws the content into a new tab

I would vote that we simply always have an "open in a separate tab" button for all of these. Seems like a really useful thing and would work pretty well by default on mobile as well.

**Comment by peterbe** [comment] 2021-01-12 17:24
> an "open in a separate tab" button for all of these.

Problem is that we don't have a URL for the content inside the `<pre>` tag. 

If it was done with a modal, you'd be able to do something like this:
```javascript
$('pre a.open').on('click', () => {
  const preCode = $(this).parent().text()
  openModal(preCode)
})
```

**Comment by chrisdavidmills** [comment] 2021-01-12 19:04
> > an "open in a separate tab" button for all of these.
> 
> Problem is that we don't have a URL for the content inside the `<pre>` tag.

Good point ;-)

> 
> If it was done with a modal, you'd be able to do something like this:
> 
> ```js
> $('pre a.open').on('click', () => {
>   const preCode = $(this).parent().text()
>   openModal(preCode)
> })
> ```

I reckon a modal would be an acceptable solution.

**Comment by schalkneethling** [comment] 2021-01-13 07:58
Wait, but it is an `iframe` with an `src` attribute right? So, we could open the `src` URL in a separate tab, no? @chrisdavidmills @peterbe

**Comment by schalkneethling** [comment] 2021-01-13 08:05
Oh wait, I was thinking of another issue 😃 

An alternative solution is to add a button that when clicked, forced the width of the `pre` block to a wider width.

### On load

![Screenshot of initial code block](https://user-images.githubusercontent.com/10350960/104423422-bffdec00-5586-11eb-8a27-b362b72a87c1.png)

### After clicking the button

We add `min-width: max-content;` that results in

![Screenshot of full width code block](https://user-images.githubusercontent.com/10350960/104423506-dad06080-5586-11eb-9b7b-6c82d17a70c7.png)

**Comment by chrisdavidmills** [comment] 2021-01-13 08:59
> An alternative solution is to add a button that when clicked, forced the width of the `pre` block to a wider width.

Hrm, that is a nice thought. Perhaps we could add that as an initial quick fix, and then look to develop it further later on?

**Comment by peterbe** [comment] 2021-01-13 20:46
3 things going on here:

1. Ability to see the whole of the inline code example
2. Ability to see the whole of a live sample
3. Ability to change the display/stretch of an inline code example. 

This issue is a mess (but full of useful discussions and thought-jots). Can someone distill it down to **1** thing or close it?

**Comment by Ryuno-Ki** [comment] 2021-01-26 18:42
> Problem is that we don't have a URL for the content inside the `<pre>` tag.

Crazy idea, but couldn't the content of `<pre>` be [read into a `Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob#example) which then gets piped into [`createObjectURL`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) which is used to open a new window?

**Comment by schalkneethling** [comment] 2021-01-27 08:59
> > Problem is that we don't have a URL for the content inside the `<pre>` tag.
> 
> Crazy idea, but couldn't the content of `<pre>` be [read into a `Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob#example) which then gets piped into [`createObjectURL`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) which is used to open a new window?

It probably could, but I guess the larger question is whether the end-user benefit will justify the engineering and maintenance effort to make this possible across all pages.

--

I know we wanted to get to something actionable so, how about we implement the suggestion here https://github.com/mdn/yari/issues/2187#issuecomment-759278250, instrument it, and have a look after 30 days or so to get an idea of how many people use the feature.

**Comment by Ryuno-Ki** [comment] 2021-01-27 17:53
Looking at data is almost always a good idea to make a decision :-)

**Comment by chrisdavidmills** [comment] 2021-02-01 07:50
> I know we wanted to get to something actionable so, how about we implement the suggestion here [#2187 (comment)](https://github.com/mdn/yari/issues/2187#issuecomment-759278250), instrument it, and have a look after 30 days or so to get an idea of how many people use the feature.

Yes, I totally think we should do this! Nice one @schalkneethling

**Comment by schalkneethling** [comment] 2021-02-01 08:07
> > I know we wanted to get to something actionable so, how about we implement the suggestion here [#2187 (comment)](https://github.com/mdn/yari/issues/2187#issuecomment-759278250), instrument it, and have a look after 30 days or so to get an idea of how many people use the feature.
> 
> Yes, I totally think we should do this! Nice one @schalkneethling

Alrighty, I will split this out into a separate issue. Thank you, Chris.

**Comment by peterbe** [comment] 2021-02-12 21:26
https://github.com/mdn/yari/issues/2784 is still open but the only distinct issue based on this initial discussion. Going to close now for spring cleaning.

**Closed by peterbe** 2021-02-12 21:26 UTC
