### ISSUE TITLE
redundant inline background-color on body?

### ISSUE THREAD

**Issue by mayank99** [mdn/yari#5380] opened 2022-03-01 18:24 UTC
I noticed that if you toggle the theme even once, then the `<body>` tag gets an inline style setting the background-color.
![image](https://user-images.githubusercontent.com/9084735/156226140-1c702453-b9de-4cce-b15d-5eef5b4681fb.png)

Likely because of the following code:
https://github.com/mdn/yari/blob/4136f02846b127b580630ff05f6081bc208ef0e0/client/public/index.html#L103-L109

Is this inline style needed? It is using hardcoded color strings, which could get out of sync with the CSS custom properties. On fresh load (nothing in localStorage), this inline style is absent and everything looks fine and correctly themed. If I comment out the line, then it still looks fine. If there is an edge case that this code is solving, then maybe it should reference the CSS variables?

I only noticed this because I was overriding the `--background-color` CSS variable to customize the look 😅 

P.S. Awesome work on the redesign 💜

**Comment by schalkneethling** [comment] 2022-03-08 13:14
@mayank99 - Thank you for bringing up this issue. This is actually intentional to avoid a flicker when switching between modes on initial load. As this is not a bug I will go ahead and close this one. Thanks again.

**Comment by schalkneethling** [comment] 2022-03-08 13:14
> P.S. Awesome work on the redesign 💜

Thank you!

**Closed by schalkneethling** 2022-03-08 13:14 UTC
Labels: redesign
