### ISSUE TITLE
Suggestion: Persist language selection

### ISSUE THREAD

**Issue by mt-webdev** [mdn/yari#5498] opened 2022-03-07 08:09 UTC
# Summary

Unfortunately, the language selection is not being persisted, which means on every visit I have to reselect my wanted language (which is English)

## Where did you spot the bug?

Literally any site:
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

## What is the problem?

The site is currently not able to persist in the user/session settings.

## What did you expect to happen?

Once I revisit the site I would like to memorize my language selection ( & theme as well, but less of a bummer)

## Steps to reproduce the issue

1. Open https://developer.mozilla.org/... in Chrome
2. use the language selector on the top right opposite of the breadcrumbs.
3. close the site
4. a couple of hours/days later re-visit

### Device

- [x ] Desktop
- 
### Browser

- [ x] Chrome: 98.0.4758.109

### Operating system

- [ x] Mac OS: 12.2.1

**Comment by schalkneethling** [comment] 2022-03-07 09:11
> Unfortunately, the language selection is not being persisted, which means on every visit I have to reselect my wanted language (which is English)

I am guessing you mean when leaving MDN and later returning via a search result? It seems to work fine if you change the language and navigate around MDN. Thank you for reporting @mt-webdev

**Comment by caugner** [comment] 2022-03-09 18:28
@mt-webdev Would it be a solution for you to make English the preferred language in your Chrome settings?

And if not, why not?

<img width="978" alt="image" src="https://user-images.githubusercontent.com/495429/157506921-43a101e0-71c2-4af5-812a-f14be5b17c43.png">

**Comment by mt-webdev** [comment] 2022-03-09 20:01
@schalkneethling yes, that's also a scenario where it's changing my preferences. (visit via Search-Engines)
@caugner I would like to keep my browser settings as is.

**Comment by caugner** [comment] 2022-03-09 20:09
@mt-webdev Just to understand: Can you elaborate on why you like to keep your browser preferring a different language than you actually prefer? Are there other sites that would then appear in English, although you prefer them in the language currently preferred by your browser?

(Note that, at least in Firefox, you can have the browser UI in one language and still prefer a different language.)

**Comment by schalkneethling** [comment] 2022-03-10 09:01
> @mt-webdev Would it be a solution for you to make English the preferred language in your Chrome settings?
> 
> And if not, why not?

I believe the problem is that the reader wants to have MDN Web Docs always in English. If they change the setting in Chrome, then I believe all(or most) websites they visit will honour the selection and always show English content.

**Comment by schalkneethling** [comment] 2022-03-10 09:06
> @schalkneethling yes, that's also a scenario where it's changing my preferences. (visit via Search-Engines)

Yes, that is a problem we have not solved for. With that said, there is a rather old pull request that does address this:
https://github.com/mdn/yari/pull/3968

We would need to pick this up again and get it merged but, we will have to speak with the product owner to set priority for when we do this work.

**Comment by apapsch** [comment] 2022-03-14 10:40
English content is usually more up-to-date, hence the preference of English on MDN, whereas the browser is set to prefer another language. In the old MDN, the problem was solved eventually by making it easy to access the English page (a link in the top right corner, "Go to English page") and IIRC the choice was saved.

**Comment by schalkneethling** [comment] 2022-03-15 09:21
> English content is usually more up-to-date, hence the preference of English on MDN, whereas the browser is set to prefer another language. In the old MDN, the problem was solved eventually by making it easy to access the English page (a link in the top right corner, "Go to English page") and IIRC the choice was saved.

I do not believe the choice was saved but yes, the quick link to English was useful to some folks. We can solve this problem by taking the following pull request across the finish line, so to speak. https://github.com/mdn/yari/pull/3968

We will need to prioritise the work though. @HerminaC and @fiji-flo Thoughts?

**Comment by mt-webdev** [comment] 2022-03-15 09:30
I never noticed this "issue" while using the previous MDN version. I am not sure why I end up on (in my case) german MDN sometimes... :-/

**Comment by NHerw** [comment] 2022-05-02 07:31
Now that we also have MDN Plus in german speaking countries, can we save our preferred language in our mozilla account?

**Comment by schalkneethling** [comment] 2022-05-16 20:46
@mt-webdev Thank you for starting this conversation. I have moved this to a discussion here: https://github.com/orgs/mdn/discussions/97

**Closed by schalkneethling** 2022-05-16 20:46 UTC
Labels: localization, 🌱 feature-request, needs-triage, need more info
