### ISSUE TITLE
Shader sample not working

### ISSUE THREAD

**Issue by MichaelPStimpson** [mdn/yari#10714] opened 2024-03-12 17:12 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_on_the_web/GLSL_Shaders

### What specific section or headline is this issue about?

Result -> Play

### What information was incorrect, unhelpful, or incomplete?

Running the sample shows the error "THREE is not defined".

### What did you expect to see?

A sample shader using three.js

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/techniques/3d_on_the_web/glsl_shaders`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_on_the_web/GLSL_Shaders
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/techniques/3d_on_the_web/glsl_shaders/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by caugner** [comment] 2024-03-15 11:38
This is a duplicate of #9346 and #10273, but I'm keeping this open for visibility.

**Comment by pseudopilot** [comment] 2024-06-01 20:10
@caugner , I think this particular bug was fixed by https://github.com/mdn/yari/pull/11017.

**Comment by caugner** [comment] 2024-06-03 09:48
Thank you @pseudopilot, it looks like this was indeed fixed by https://github.com/mdn/yari/pull/11017. 🎉

**Closed by caugner** 2024-06-03 09:48 UTC
Labels: 🐛 bug, p2, regression, plus:playground
