### ISSUE TITLE
huge avatar in header

### ISSUE THREAD

**Issue by cadeyrn** [mdn/yari#9036] opened 2023-06-08 06:34 UTC
### Summary

The header shows a huge avatar.

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

1. Open the MDN.
2. Log in.

### Expected behavior

Normal sized avatar.

### Actual behavior

Huge avatar.

### Device

Desktop

### Browser

Firefox

### Browser version

Pre-release (e.g. Beta, Nightly or Canary)

### Operating system

Mac OS

### Screenshot

<img width="638" alt="Bildschirmfoto 2023-06-08 um 08 27 10" src="https://github.com/mdn/yari/assets/1100614/770bcb59-a5f6-47be-8a29-c55a85df0319">

### Anything else?

It's a recent regression, I never seen this before. But it does not always happen:

I did a hard reload a few times, maybe 25 times. Four or five times the avatar had the correct size, but most times the avatar was huge.

When it happens and I inspect the code in the developer tools the following CSS is completely missing:

```
.avatar-wrap {
  height: 32px;
  margin-left: -7px;
  margin-right: .1rem;
  position: relative;
  width: 32px;
}
```

And the CSS is loaded from https://developer.mozilla.org/static/css/main.32bad2bb.css. When it works as expected the URL is https://developer.mozilla.org/static/css/main.799c3a05.css instead.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment] 2023-09-28 12:30
I cannot reproduce the issue (even if hard-reloading a couple of times), but I have seen it before, so I think we need more info.

@cadeyrn Do you have MDN Offline enabled by any chance? Or do you see any console or network errors when this happens?

**Comment by cadeyrn** [comment] 2023-09-28 19:53
No, MDN Offline is not enabled. But I can no longer reproduce the issue, so I'm afraid I can't provide any more information.

**Comment by caugner** [comment] 2023-09-28 22:23
Glad to hear! And in fact it was a the regression caused by https://github.com/mdn/yari/pull/9023 and fixed by https://github.com/mdn/yari/pull/9038 (see [this comment](https://github.com/mdn/yari/pull/9038#issuecomment-1582077705)).

**Closed by caugner** 2023-09-28 22:23 UTC
Labels: 🐛 bug, needs info
