### ISSUE TITLE
Long word in sidebar class in nav tag

### ISSUE THREAD

**Issue by XMoSalahX** [mdn/yari#4795] opened 2021-10-14 13:15 UTC
This problem is common on-site pages, for example on this page:
[MDN Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

1. Look on this method on sidebar : `Number.prototype.toLocaleString()`
2. Change the screen width between `"1100px : 1008px"`

**You will find that: the long word exceeds the size of the container.**

**- [:white_check_mark: ] To solve the problem:**

- Replace the stylesheet file with this file

[main.a43ed10c.chunk2.zip](https://github.com/mdn/yari/files/7346218/main.a43ed10c.chunk2.zip)

**Comment by escattone** [comment] 2021-10-19 23:47
Thanks for letting us know @XMoSalahX. We're planning on improving the sidebars in the next few months.

Duplicate of #4635

**Comment by schalkneethling** [comment] 2022-01-11 20:08
Thank you for reporting @XMoSalahX. This is being addressed as part of the redesign that is currently underway. The work is tracked in a separate repo though, so I am going to close this one here. If after the redesign is launched you do find instances of this, feel free to reopen this. Thanks again.

**Closed by schalkneethling** 2022-01-11 20:08 UTC
