### ISSUE TITLE
XML Sitemap files are invalid

### ISSUE THREAD

**Issue by a-kyne** [mdn/yari#6965] opened 2022-07-13 18:15 UTC
**Summary**
Although the Sitemap index file is valid ( https://developer.mozilla.org/sitemap.xml), none of the three XML files it links to are valid.

**Steps To Reproduce (STR)**

1. Visit the following URLs:

- https://developer.mozilla.org/sitemaps/fr/sitemap.xml.gz
- https://developer.mozilla.org/sitemaps/en-us/sitemap.xml.gz
- https://developer.mozilla.org/sitemaps/ja/sitemap.xml.gz

2. Attempt to open the files.

**Actual behavior**
File does not open as XML. "Encoding error"

**Expected behavior**
I should be able to open the files and validate the XML.

**Additional context**

**Comment by caugner** [comment] 2022-09-05 18:17
Duplicate of https://github.com/mdn/yari/issues/6708.

**Closed by caugner** 2022-09-05 18:17 UTC
Labels: needs-triage
