### ISSUE TITLE
A decent CSS grid

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#59] opened 2019-07-25 20:48 UTC
We currently have a super basic CSS skeleton based on [water.css](https://watercss.netlify.com/) plus our own dumping groud [`mdn.scss`](https://github.com/mdn/stumptown-renderer/blob/master/client/src/mdn.scss) where we've ported some necessary CSS stuff to display the pages correctly. 

What would be nice is a ground-up solid CSS framework with a decent grid and a decent header and footer. 
It should be responsive at least.

**Comment by schalkneethling** [comment] 2019-07-26 08:04
Happy to take this one.

**Comment by peterbe** [comment] 2020-06-03 17:41
Perhaps this needs to be renamed to a task etc. Perhaps it should be called "Incorporate minimalist in Yari" or "Rewrite SCSS framework" :)

**Comment by schalkneethling** [comment] 2020-06-04 08:47
> Perhaps this needs to be renamed to a task etc. Perhaps it should be called "Incorporate minimalist in Yari" or "Rewrite SCSS framework" :)

I notice that this one is assigned to me https://github.com/mdn/yari/issues/708 🤷‍♂️

**Comment by tobinmori** [comment] 2020-07-21 17:18
Replaced by design system

**Closed by tobinmori** 2020-07-21 17:18 UTC
