### ISSUE TITLE
Left navigation pane

### ISSUE THREAD

**Issue by shariq786-source** [mdn/yari#8513] opened 2023-03-27 14:12 UTC
### Summary

The left navigation pane on MDN docs website doesn't scroll unless the browser window size gets reduced to 80%. Issue occurs on Chrome, Edge and Firefox browsers. 

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML

### Reproduction steps

1. Open MDN Docs web page
2. Navigate to HTML page
3. Scroll through page but left pane doesnt scroll

### Expected behavior

For left pane to move when mouse hovers over and scrolls

### Actual behavior

Left pane doesnt move when hovering mouse and scrolling

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment] 2023-03-28 11:24
This is a duplicate of https://github.com/mdn/yari/issues/8494 and has been fixed via https://github.com/mdn/yari/pull/8512 yesterday.

**Closed by caugner** 2023-03-28 11:24 UTC
Labels: needs triage
