### ISSUE TITLE
When I use the OS Default theme, the light / dark style disappears in chrome86

### ISSUE THREAD

**Issue by zhouhaoyiu** [mdn/yari#6135] opened 2022-05-02 04:48 UTC
### Summary

When I use the OS Default theme, the light / dark style disappears.
Browser: 360chrome
Version No.: 13.5.2001.0
Kernel version: 86.0.4240.198
This browser can be downloaded in https://browser.360.cn/ee/index.html , you should download the official version.

### URL

https://developer.mozilla.org/zh-CN/docs/MDN/About

### Reproduction steps

1. Open this URL in this browser.
2. Switch theme to OS default.

### Expected behavior

Light \ Dark style should exist,like this
![light](https://user-images.githubusercontent.com/67226385/166185599-8e410e51-df03-45ed-82d9-b497357e6ca3.png)

### Actual behavior

Light \ Dark style disappears.
![OSD](https://user-images.githubusercontent.com/67226385/166185614-1c6a13d8-7667-4aa7-b766-73d7bffcc13c.png)

### Device

Desktop

### Browser

Other (specify below)

### Browser version

Stable

### Operating system

Windows

### Screenshot

https://user-images.githubusercontent.com/67226385/166183437-47d21fe9-dc32-462c-937e-af4805eae5bd.mp4

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by zhouhaoyiu** [comment] 2022-05-02 04:52
If the recording screen seems to have no content, you can download the video and open it.

**Comment by caugner** [comment] 2022-05-02 18:51
It looks like the browser you're using does not support [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme).

@zhouhaoyiu Could you please check out https://www.davidwalsh.name/demo/css-supports.php in 360chrome and see if you see the following (green) message:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/495429/166307281-200c0167-39f9-43bd-8f32-e643d399e031.png">

If so, we might be able to add a fallback for browsers not supporting `prefers-color-scheme`.

**Comment by zhouhaoyiu** [comment] 2022-05-02 18:56
> https://www.davidwalsh.name/demo/css-supports.php
![25556](https://user-images.githubusercontent.com/67226385/166307935-0aa7d2c0-61ec-401b-b403-4035c3ebd65b.png)

**Comment by caugner** [comment] 2022-05-03 10:29
Thank you! Now, unfortunately CSS doesn't allow us to combine `@supports` with `@media (prefers-color-scheme: dark)`, but given that 360chrome 13.5 is using Chrome 86, it should have support for `prefers-color-scheme` anyways.

@zhouhaoyiu Could you please try if the following resolves the issue for you:
1. Open MDN and reproduce the issue.
2. Open the browser DevTools.
3. Switch to the "Sources" tab (which shows a file tree on the left).
4. Search for "_themes.scss".
5. Replace `@media (prefers-color-scheme: light) {` on lie 361 to `@media not (prefers-color-scheme: dark) {`
6. Press CTRL + S to save the file.

**Comment by zhouhaoyiu** [comment] 2022-05-03 10:44
I've replaced it and saved it, but nothing seems to have changed
![replace](https://user-images.githubusercontent.com/67226385/166440093-2d1c99b4-6cce-40b0-a2e5-5cd6d1a5962b.png)

**Comment by zhouhaoyiu** [comment] 2022-05-03 10:45
> Thank you! Now, unfortunately CSS doesn't allow us to combine `@supports` with `@media (prefers-color-scheme: dark)`, but given that 360chrome 13.5 is using Chrome 86, it should have support for `prefers-color-scheme` anyways.
> 
> @zhouhaoyiu Could you please try if the following resolves the issue for you:
> 
> 1. Open MDN and reproduce the issue.
> 2. Open the browser DevTools.
> 3. Switch to the "Sources" tab (which shows a file tree on the left).
> 4. Search for "_themes.scss".
> 5. Replace `@media (prefers-color-scheme: light) {` on lie 361 to `@media not (prefers-color-scheme: dark) {`
> 6. Press CTRL + S to save the file.

I've replaced it and saved it, but nothing seems to have changed
![replace](https://user-images.githubusercontent.com/67226385/166440093-2d1c99b4-6cce-40b0-a2e5-5cd6d1a5962b.png)

**Comment by zhouhaoyiu** [comment] 2022-05-03 10:52
And I found that my avatar sometimes disappear. 😂😂😂
![avatar](https://user-images.githubusercontent.com/67226385/166441040-789390eb-a036-4d4a-b389-f1a3abd01719.png)
s

**Comment by caugner** [comment] 2022-05-03 11:05
> And I found that my avatar sometimes disappear.

Did you upload an avatar in your Firefox account, or are you using Gravatar?

**Comment by zhouhaoyiu** [comment] 2022-05-03 11:08
> > And I found that my avatar sometimes disappear.
> 
> Did you upload an avatar in your Firefox account, or are you using Gravatar?
My avatar is like this.
![myavatar](https://user-images.githubusercontent.com/67226385/166442799-927e45d1-c830-4431-8f59-9c70831f70d9.png)

**Comment by zhouhaoyiu** [comment] 2022-05-03 15:25
I tested it with four browsers. My avatar only displays wrong in 360chrome 13. May I need to stop using it? lol
![test](https://user-images.githubusercontent.com/67226385/166484112-aea88187-573c-47ed-a036-43da46d2f93f.png)

**Comment by zhouhaoyiu** [comment] 2022-05-03 15:30
> I tested it with four browsers. My avatar only displays wrong in 360chrome 13. May I need to stop using it? lol ![test](https://user-images.githubusercontent.com/67226385/166484112-aea88187-573c-47ed-a036-43da46d2f93f.png)

The bug that caused the style to disappear only appeared in 360chrome 13 also.It puzzles me.

**Comment by caugner** [comment] 2022-05-03 15:51
Thanks again for reporting this issue, @zhouhaoyiu.

As for the missing avatar, your browser or an extension might be blocking the Gravatar image. The browser console may have a corresponding warning or error message.

As for the theme, it looks very much like a bug in 360chrome, because Chrome 86 already supported `prefers-color-scheme`. But as 360chrome seems to using an outdated Chrome version, and we don't officially support 360chrome, I will indeed go ahead and close this issue.

As a workaround, I recommend either choosing a specific theme, or using a different browser.

**Comment by zhouhaoyiu** [comment] 2022-05-03 15:59
> Thanks again for reporting this issue, @zhouhaoyiu.
> 
> As for the missing avatar, your browser or an extension might be blocking the Gravatar image. The browser console may have a corresponding warning or error message.
> 
> As for the theme, it looks very much like a bug in 360chrome, because Chrome 86 already supported `prefers-color-scheme`. But as 360chrome seems to using an outdated Chrome version, and we don't officially support 360chrome, I will indeed go ahead and close this issue.
> 
> As a workaround, I recommend either choosing a specific theme, or using a different browser.

Thanks for patiently answering my questions and I have reported this bug to the 360chrome team.

**Comment by zhouhaoyiu** [comment] 2022-05-06 17:49
I used chrome 86 and found that this bug still exists @caugner
![9B2E6C12-9D72-4BEC-88D6-ADC6B85010C2](https://user-images.githubusercontent.com/67226385/167187798-468f5639-22aa-40ef-b168-476dca26fa95.gif)

**Comment by zhouhaoyiu** [comment] 2022-05-07 02:57
> 360chrome community moderator reply
![reply](https://user-images.githubusercontent.com/67226385/167235312-07c0826a-1e8e-409d-bcc9-347231df3fcf.png)

**Comment by caugner** [comment] 2022-05-10 10:48
This issue is caused by the fact that Chrome 86 does not yet support `:not()` (see https://developer.mozilla.org/en-US/docs/Web/CSS/:not#browser_compatibility), and this is what we're using here:

https://github.com/mdn/yari/blob/68fc2b46ad95f3a41dcdd17cba468047ab3ecc05/client/src/ui/base/_themes.scss#L360-L368

**Comment by teoli2003** [comment] 2022-05-10 10:51
I updated the mdn page last week. So I think `:root(.light):not(.dark)` should do it (drive-by comment ;-) )

**Comment by zhouhaoyiu** [comment] 2022-05-10 11:26
> I updated the mdn page last week. So I think `:root:not(.light):not(.dark)` should do it (drive-by comment ;-) )

Thank you. Now the theme is displayed normally.

**Closed** 2022-05-10 12:17 UTC
Labels: needs-triage, dark-mode, 3rd-party
