### ISSUE TITLE
article scroll sidebar reference pointing to wrong section than where it actually is on page

### ISSUE THREAD

**Issue by bappyasif** [mdn/yari#6064] opened 2022-04-25 18:04 UTC
article link: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Transformations

![image](https://user-images.githubusercontent.com/19854521/165146566-db9d2a0e-a0f7-422d-843c-b2ef5b24e337.png)

as i mentioned in this title already, scrolling position on 'article page' does not reflect properly with 'scroll sidebar reference', its lacking behind at-least two section from where it should be pointing to, thanks....

platform details: 
os: ubuntu
computer: notepad
browser: chrome

**Comment by schalkneethling** [comment] 2022-04-25 18:12
Thank you again for filing an issue. After looking at existing issues, we have identified this as a duplicate of #6041. Therefore, we have referenced this issue in the original and will close this as a duplicate.

**Closed by schalkneethling** 2022-04-25 18:12 UTC
Labels: needs-triage, sidebar/toc
