### ISSUE TITLE
A link with anchor is not focused

### ISSUE THREAD

**Issue by artur-intech** [mdn/yari#9783] opened 2023-05-13 13:23 UTC
When I open a link with an anchor inside it, i.e. `https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#browser_compatibility`, I expect the corresponding section to be focused once the page is loaded.

However, automated focusing is not working unless I explicitly click on a link in the "In this article" section.

I tried it in Chrome and Edge and the result is always the same, whereas on other websites it works as expected.

Is it my machine or there is something wrong with MDN itself? I was unable to find anything suspiciously-looking in the HTML I briefly checked.

**Comment by caugner** [comment] 2023-10-09 18:42
Thanks for reporting this issue @artur-intech, and sorry for taking so long to respond!

This seems to be a duplicate of https://github.com/mdn/yari/issues/7168 and/or https://github.com/mdn/yari/issues/8049.

**Closed by caugner** 2023-10-09 18:42 UTC
Labels: needs triage
