### ISSUE TITLE
Page Using HTTP cookies Russian language Error 404

### ISSUE THREAD

**Issue by DukeBJ** [mdn/yari#2391] opened 2020-12-28 09:05 UTC
Hi.
If you switch the page "Using HTTP cookies" to Russian, then in response you see "Error: 404 on /ru/docs/Web/HTTP/Cookies/index.json: Page not found"

**Comment by peterbe** [comment] 2021-01-07 22:47
It's the unicode characters in https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%9A%D1%83%D0%BA%D0%B8
@escattone Do you remember what's the ups with this? 
Forcing all translated content to English slugs is going to reduce the problem (hi @fiji-flo ) but it won't go away because I could be having `https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%9A%D1%83%D0%BA%D0%B8` bookmarked (the redirect will probably also fail)

**Comment by peterbe** [comment] 2021-01-07 22:48
Technically this is a duplicate of https://github.com/mdn/yari/issues/2173
But we can carry on the conversation in either.

**Comment by peterbe** [comment] 2021-01-07 22:48
Also, if you enable the `CONTENT_TRANSLATED_ROOT` in local dev, http://localhost:3000/ru/docs/Web/HTTP/%D0%9A%D1%83%D0%BA%D0%B8 works fine.

**Comment by peterbe** [comment] 2021-01-07 22:52
https://s3.console.aws.amazon.com/s3/object/mdn-content-prod?region=us-west-2&prefix=main/ru/docs/web/http/%D0%BA%D1%83%D0%BA%D0%B8 is there. 
I think it just hasn't been made into lowercase.

**Comment by escattone** [comment] 2021-01-25 22:30
I updated the `dev`, `stage`, and `prod` CloudFront instances to use the new Lambda@Edge function from https://github.com/mdn/yari/pull/2545. This is resolved.

**Closed by escattone** 2021-01-25 22:30 UTC
Labels: duplicate
