### ISSUE TITLE
Loop redirection between two URLs

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#11080] opened 2024-05-07 02:18 UTC
### Summary

Got a loop redirection between the following URLs:

- https://developer.mozilla.org/en-US/docs/Web/API/Window/performance
- https://developer.mozilla.org/en-US/docs/Web/API/performance_property

This may be related to mdn/content#33339.

### URL

- https://developer.mozilla.org/en-US/docs/Web/API/Window/performance
- https://developer.mozilla.org/en-US/docs/Web/API/performance_property

### Reproduction steps

1. Open browser with devtools opened in Network panel
2. navigator to <https://developer.mozilla.org/en-US/docs/Web/API/Window/performance>
3. See network logs

Note, clearing website data cannot resolve this problem, it seems to be a server-side problem.

### Expected behavior

Won't get a loop redirection, and this page can be opened as normal.

### Actual behavior

Got a loop redirection.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://github.com/mdn/yari/assets/15844309/1e35447f-0945-4901-bdf2-5ea77e942c99)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by bsmth** [comment] 2024-05-07 10:24
Already discussed on Discord, but adding a note to say I can't reproduce this, it may have been caches being invalidated during deploy.

**Comment by bsmth** [comment] 2024-05-08 08:07
For some more context, the problem appears to be from here: 

https://github.com/mdn/content/commit/dfb8c72c3e775b4a763ad5c495756e2897a46847#diff-afe010c4707d10d488b1e1c050b3298da03267dec0abca46d6d444b2ae8774a5L10890

We had a situation where these changes happened in the redirects file:

```diff
- /en-US/docs/Web/API/Window/performance /en-US/docs/Web/API/performance_property
+ /en-US/docs/Web/API/performance_property /en-US/docs/Web/API/Window/performance
```

**Comment by caugner** [comment] 2024-05-14 14:37
I cannot reproduce the issue, and indeed this indicates a temporary caching issue. We tell browsers to cache permanent redirects for moved pages for 30 days (which we could reduce), and our CDN only caches them for 30 minutes.

**Comment by argl** [comment] 2024-06-10 14:01
Also not able to reproduce here. I am closing this issue, if this persists beyond the ususal cache timeouts, feel free to re-open.

**Closed by argl** 2024-06-10 14:01 UTC
Labels: needs triage, infra
