### ISSUE TITLE
document.github_url has `master` branch in URL

### ISSUE THREAD

**Issue by bershanskiy** [mdn/yari#1966] opened 2020-12-05 14:19 UTC
Link in `contributors.txt` points to `mdn/content` branch `master`, which does not exist. It should be `main` branch.

Interestingly enough, when I run `npm run build` on local checkout, the produced files have correct URLs.

## Example

Documentation pages have associated `/contributors.txt` files which list contributors to the individual pages. For example, for [`Web/API/Window`](https://developer.allizom.org/en-US/docs/Web/API/Window) it is at [`Web/API/Window/contributors.txt`](https://developer.allizom.org/en-US/docs/Web/API/Window/contributors.txt)

Unfortunately, the link is incorrect, it has `master` in it:
```
# Contributors by commit history
https://github.com/mdn/content/commits/master/files/en-us/web/api/window/index.html
```

It should have `main` instead:
```
# Contributors by commit history
https://github.com/mdn/content/commits/main/files/en-us/web/api/window/index.html
```

**Comment by peterbe** [comment] 2020-12-08 11:35
@tannerdolby Is this something you'd can write a PR for?

**Comment by tannerdolby** [comment] 2020-12-08 18:40
@peterbe Yeah, I can write a PR for this.

**Comment by tannerdolby** [comment] 2020-12-08 21:23
It seems `contributors.txt` is being rendered server side in `server/index.js` with `res.send()`. The `renderContributorsTxt()` function in `build/index.js` uses the `githubURL` like so:

```
if (githubURL) {
    // Always show this first
    txt += `# Contributors by commit history\n${githubURL}\n\n`;
  }
```
Since the `github_url` is being created inside the `injectSource(doc, document)` function using `getGitHubURL`,  I think it's probably best to leave `build/index.js` alone for now and perform the URL replacement inside `server/index.js` or `build/cli.js` because this is where we actually provide the `renderContributorsTxt` arguments for `wikiContributorNames` and `githubURL`.

The `renderContributorsText` function is being imported into `build/cli.js` as:

```
const { buildDocument, renderContributorsTxt } = require("./index")
```
which I'm assuming is grabbing the `index.json` data file. Where `server/index.js` is importing `renderContributorsText` from `../build` and grabs the function.

The URL replacement for "blob" happens both in `build/cli.js` and `server/index.js`. Since the result is being sent in `server/index.js` using `res.send(renderContributorsTxt..)` and the file is being written in `cli.js`, I wasn't entirely sure whether both of these locations needed to have the URL updated.

### Fix:
The GitHub URL, `builtDocument.source.github_url` has `/blob/` being replaced with `/commits/`. 

I was thinking of just writing another `.replace` method to swap `/master/` with `/main/`.

Notes:
The function `getGitHubURL` in `/build/index.js` that is using `getCurrentGitBranch(root)` to supply the Git branch, I think this is where the master and main mixup is happening.
```
${baseURL}/blob/${getCurrentGitBranch(
    root
  )}/files/${folder}/index.html` 
```

**Comment by peterbe** [comment] 2020-12-09 02:43
You're right in that the problem is deeper. It's actually got nothing to do with the `contributors.txt` output. 
The problem is that `builtDocument.source.github_url` is wrong. 
You can see it here: https://developer.allizom.org/en-US/docs/Web#on-github
It links to https://github.com/mdn/content/blob/master/files/en-us/web/index.html but if you click, GitHub will gracefully redirect you to https://github.com/mdn/content/blob/main/files/en-us/web/index.html

If you follow the trail you'll see `getGitHubURL` calls `getCurrentGitBranch()` which gets it wrong.

**Comment by peterbe** [comment] 2020-12-09 03:03
I think the problem is that we might be trying to be too smart. When it builds in production (the most important build),
it all starts with a GitHub Action workflow that runs on a cronjob. It checks out the `master` branch of `mdn/yari` and within that workflow, it checks out the `main` branch of `mdn/content`. But I suspect that what's happening is that `process.env.GITHUB_REF` refers to the ref of the `mdn/yari` branch, not the `mdn/content` one. 

I suspect that this function actually dates back to the early days when the build JS code was all in the same repo as the en-US content. Then, it kinda made sense that the `github_url` for each document could be assumed to be same git checkout as that for the code. 

@tannerdolby This issue might become complex and I intend to take an active role in solving it. But please stick around!

@escattone I've labelled this as a milestone blocker.

**Comment by tannerdolby** [comment] 2020-12-09 05:27
@peterbe Ok, yeah I was beginning to think `contributors.txt` and `renderContributorsTxt` was not part of the problem. After following the trail earlier today, I discovered `getGitHubURL` in `build/index.js` which is using `${getCurrentGitBranch(root)}` and this is where the deeper issue occurs like you stated above.

> But I suspect that what's happening is that process.env.GITHUB_REF refers to the ref of the mdn/yari branch, not the mdn/content one

I think your correct that within the GitHub Action workflow and cronjob, its checking out the `master` branch of `mdn/yari` and `main` branch in `mdn/content`. 

Then `getCurrentGitBranch` is grabbing `master` from `mdn/yari` instead of `main` from `mdn/content` since `process.env.GITHUB_REF` refers to the ref of the `mdn/yari` branch causing the mixup.

**Comment by tannerdolby** [comment] 2020-12-09 05:27
> This issue might become complex and I intend to take an active role in solving it. But please stick around!

Sounds good. I will stick around.

**Comment by Ryuno-Ki** [comment] 2021-02-13 14:01
I can see an open issue #2277. But it doesn't look like anybody would work on a fix?

**Comment by tannerdolby** [comment] 2021-02-13 20:06
I think @peterbe was working on a fix for this as the issue was a little bit more involved.

**Comment by mattiapontonio** [comment] 2021-02-14 16:36
Being that this renaming is a [global issue](https://www.google.com/search?q=github+master+main+change) I share this [research](https://github.com/mdn/yari/search?q=master&type=) to understand if you can do a _local but globally adjustment in this repository_, without considering possibly URLs coming from other sources of course.

**Comment by peterbe** [comment] 2021-02-16 16:51
[`master` is gone](https://github.com/mdn/yari/discussions/2951)

**Closed by peterbe** 2021-02-16 16:51 UTC
