### ISSUE TITLE
"Related topics" Navigation overlapping the content

### ISSUE THREAD

**Issue by d11r** [mdn/yari#5008] opened 2021-11-27 14:51 UTC
![image](https://user-images.githubusercontent.com/17767170/143686226-9210448d-73a9-4e2a-8391-cd7541ce199c.png)

URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
Browser width: 1240px

**Comment by wbamberg** [comment] 2022-01-12 01:00
Duplicate of https://github.com/mdn/yari/issues/4973.

**Closed by wbamberg** 2022-01-12 01:00 UTC
Labels: needs-triage
