### ISSUE TITLE
Show bad_bcd_queries flaw in renderd HTML ...also

### ISSUE THREAD

**Issue by bershanskiy** [mdn/yari#2066] opened 2020-12-10 20:58 UTC
Sometimes calls to `{{Compat("...")}}` macros are incorrect because writers make typos and copy-paste content between pages and forget to update macros.

For context, here are few fixes from [the last content dump](https://github.com/mdn/content/commit/65ad885ac2a3ff08f9b5b5b3131e0821e38c5e13):
 - Wrong BCD entry caused by copy-paste: [one](https://github.com/mdn/content/commit/65ad885ac2a3ff08f9b5b5b3131e0821e38c5e13#diff-d4ab54dee5da37ee72df2152cc01af4478621e014285c12dcbdbaf05b289d2dc), [two](https://github.com/mdn/content/commit/65ad885ac2a3ff08f9b5b5b3131e0821e38c5e13#diff-56b8fd5ecb3f654b21fe49ff0d1b31318176f5906de676bb033a23b021d404e0)
 - Wrong interface with a similar name: [one](https://github.com/mdn/content/commit/65ad885ac2a3ff08f9b5b5b3131e0821e38c5e13#diff-5deee8e94a37d39e79e95236bd9c362eef329dc7babc7a926260544b50a27a70), [two](https://github.com/mdn/content/commit/65ad885ac2a3ff08f9b5b5b3131e0821e38c5e13#diff-45436b626c5ce68b9a02f7d351d7f60b8cc8c3096ca6b95e9253cbe7aa7baa8f)
 - Broken calls: [one](https://github.com/mdn/content/commit/65ad885ac2a3ff08f9b5b5b3131e0821e38c5e13#diff-470eb038812604cc4076d5466e13187ac228cb4602871411ad380b402e943fcc)
 - Sometimes BCD entries get moved and content should be updated accordingly

It would be nice if Yari compared `mdn/content` `Compat` calls to `mdn/browser-compat-data` `mdn_url`s. I have in mind these checks:
 - extract the first argument from `Compat` call and check that BCD entry that it describes exists and its `mdn_url` is comparable to the document's path.
 - Check that if BCD entry points to a page, it's included on the page. This requires requires complete traversal of BCD to build a map of `mdn_url`s to their paths within BCD.

Note that multiple BCD entries might point to one page and a page might contain multiple BCD tables.

**Comment by jpmedley** [comment] 2020-12-11 17:53
Regardless of the approach, some kind of checking along these lines would be valuable.

**Comment by peterbe** [comment] 2020-12-11 18:27
Technically, we already do this. There's a flaw check called `bad_bcd_queries` which should trigger if you do something like:
```html
{{Compat("api.SpeechSynthesis.kancell")}
```
or even if you don't typo it but it simply doesn't exist in `@mdn/browser-compat-data`. 

But I'm not going to close this issue because when you do get these flaws, in production builds, it just hides the whole "Browser Compatibility" section. That's a bit weird and can be improved. It probably would serve users (aka readers) a bit better to know that there is hope! :)

For compare http://localhost:3000/en-US/docs/Web/API/AddressErrors/addressLine#_flaws with https://developer.mozilla.org/en-US/docs/Web/API/AddressErrors/addressLine
What you see is this:
<img width="1477" alt="Screen Shot 2020-12-11 at 1 21 53 PM" src="https://user-images.githubusercontent.com/26739/101940110-fc1ee500-3bb3-11eb-80a6-69f952edee47.png">

I'd rather it displays *something* in the HTML than just this nothingness. I think of the people who look for BCD data, there's a stronger chance that someone might react constructively if they see something's missing. A quick click to the `mdn/browser-compat-data` project might be first thing to do fix that cap. Or if they spot "Ah! I see what's going. It's a typo!" they should be inspired to go to github.com/mdn/content to fix it. 

I actually think, it's a "pre-launch regression" (I made that term up). It used to display something in the page, but it stopped working at some point. 

ALso, I don't know if you've seen this, but there's a "Flaws Dashboard" which can analyze ALL built documents and all the flaws found. Here's what I'm seeing at the moment after having built all the `web/api` docs in `en-US`:
<img width="1404" alt="Screen Shot 2020-12-11 at 1 26 31 PM" src="https://user-images.githubusercontent.com/26739/101940463-88c9a300-3bb4-11eb-95bb-a16567077dfa.png">

I think the foundations are there. We just need to improve it a bit (...post-launch).

**Comment by jpmedley** [comment] 2020-12-11 18:43
Is there any checkin the command-line workflow for submitting a PR? I think that would be the ideal place to prevent the submission of new errors.

**Comment by peterbe** [comment] 2020-12-11 19:18
> Is there any checkin the command-line workflow for submitting a PR? I think that would be the ideal place to prevent the submission of new errors.

Are you asking if we're logging and checking for flaws during PRs? We are not. And it's kinda sad. 
See https://github.com/mdn/content/blob/c79bf8d3b1566b444a255527603a304bf6d3624d/.github/workflows/pr-build.yml#L55-L59
which links to https://github.com/mdn/yari/issues/715 which is already old. 
But basically, we need to come back to this because it's sort of the core idea with this flaw checking stuff. The reason/excuse is just lack of time. It's also a bit tricky to break someone's PR for a flaw in a piece of the HTML that you didn't even touch in your PR and we'll need to do everything we can to avoid that. 

Also, if you write some CI code, it's easy to communicate back to the PR simply by `exit 0` or `exit 1` and GitHub takes care of putting up little green checkmarks or red crosses. But throwing warnings is harder. And in particular, I think what you want is a bot that can post comments back to the author of the PR. We'll get there.

**Comment by peterbe** [comment] 2021-04-21 00:31
The PR Review Companion will now show all possible flaws as a PR comment.

**Closed by peterbe** 2021-04-21 00:31 UTC
Labels: Post-launch, enhancement
