### ISSUE TITLE
Header in weird comic sans font

### ISSUE THREAD

**Issue by its-pablo** [mdn/yari#7627] opened 2022-11-19 18:12 UTC
### Summary

![image](https://user-images.githubusercontent.com/78528552/202823719-6e7d2625-75a0-4f9d-88a4-60eaaf1aeab7.png)
The options header is in a weird small comic sans font. I tried fixing this myself but I couldn't really tell what was wrong; it seemed fine in the md file

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API

### Reproduction steps

open the site above in chrome 103

### Expected behavior

Just a normal heading

### Actual behavior

Small comic sans font

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Other (specify below)

### Screenshot

![image](https://user-images.githubusercontent.com/78528552/202823719-6e7d2625-75a0-4f9d-88a4-60eaaf1aeab7.png)

### Anything else?

Originally opened in https://github.com/mdn/content/issues/22405

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment] 2022-11-20 22:24
Hi @its-pablo, thanks for reporting this issue. 👋 

> **Operating system**: Other (specify below)

What OS are you running? Can you reproduce the issue in a private tab and/or in a different browser? (I quickly checked in Firefox on Android and couldn't reproduce.)

**Comment by its-pablo** [comment] 2022-11-21 03:39
Chrome 103/Chrome OS
I'll try turning off browser extensions

**Closed** 2022-11-22 02:57 UTC
Labels: needs-triage, need more info, typography
