### ISSUE TITLE
Some pages go blank

### ISSUE THREAD

**Issue by MordechaiFast** [mdn/yari#11955] opened 2024-10-13 22:05 UTC
### Summary

Some of the pages, but not all of them, on the MDN JavaScript tutorial display for half a second and then go black. Happens on Chrome for android, for Debian, and FireFox.

### URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript

### Reproduction steps

1.Go to said URL
2.Watch page go black
3.Try another browser

### Expected behavior

Have the page stay

### Actual behavior

Page shows for half a second and then goes black

### Device

Tablet (e.g. iPad)

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by argl** [comment] 2024-10-21 09:19
I cannot reproduce this on my environment, @mirunacurtean could you take a closer look at this? I do not have a Chrome-on-Android combination at hand.

**Comment by mirunacurtean** [comment] 2024-10-21 10:09
I have tried on Android 13, mobile, with chrome and FF and could not reproduce. 
Also tried with various Samsung tablet types, with Android 12 and 10 on Chrome and FF and navigated through the Javascript tutorial pages and stopped on some to see if the blank page issue can be reproduced, but it would not. 

https://github.com/user-attachments/assets/510f1db2-e0f3-43b1-a629-13686ba2072c

Maybe we need the specific device+ OS type combination, but still, this seems to be an edge case that cannot be reproduced for now.

**Comment by argl** [comment] 2024-10-22 10:26
SInce we cannot reproduce the issue and no other reports of the problem have been filed, I am closing this ticket. Thank you for taking the time to report your issue and feel free to reopen if any further details emerge.

**Closed by argl** 2024-10-22 10:26 UTC
Labels: p3, dark-mode, regression

**Comment by MordechaiFast** [comment] 2025-01-16 21:50
I found out that it was a problem with my firewall blocking the javascript
