### ISSUE TITLE
Improve the layout nd use of icons in BCD tables

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5878] opened 2022-03-31 20:40 UTC
I personally think that inconsistent icons can be good for accessibility, your example is super nice-looking but the circle icons can be a bit hard to tell apart at a quick glance if one has poor eyesight or red-green colorblindness.

Here is what yours looks like put through Chrome's deuteranopia color filter (the most common form of colorblindness):
![Šime_Vidas_MDN_AFTER](https://user-images.githubusercontent.com/57331134/160034046-fc0bd8b9-7744-46ac-8f3d-18ffbc92fbef.png)

I took a stab at making a mock-up, here is my attempt:

**Before:**

![Andrew_Grant_MDN_BEFORE](https://user-images.githubusercontent.com/57331134/160033278-fde5c31d-32a6-4459-a3b7-927ebb1b653e.png)

**After:**

![Andrew_Grant_MDN_AFTER](https://user-images.githubusercontent.com/57331134/160033294-d3da90aa-a698-4a61-b4e5-33c96d65c03a.png)

It's not as pretty as yours but the checkmark is visually distinguished from the X and question mark.

_Originally posted by @Andrew6rant in https://github.com/mdn/yari/issues/5546#issuecomment-1078552004_

**Comment by schalkneethling** [comment] 2022-03-31 20:41
@ddbeck, I would appreciate your feedback on the above proposal. Thanks!

**Comment by Andrew6rant** [comment] 2022-03-31 20:51
Thanks for posting it!

Here also is my concept put through the deuteranopia filter:

![Andrew_Grant_MDN_AFTER_DEUTERANOPIA](https://user-images.githubusercontent.com/57331134/160034979-9c625acf-1e64-4529-a545-968282934cb7.png)

**Comment by caugner** [comment] 2022-11-15 11:46
Duplicate of https://github.com/mdn/yari/issues/5804:

> In the mean-time, we have addressed the readability of the BCD tables by using circles only for no support, unknown support and pre-release feature (see [here](https://developer.mozilla.org/en-US/docs/Web/API/Window#browser_compatibility)):

**Closed by caugner** 2022-11-15 11:46 UTC
Labels: ♿ a11y, needs: decision from design, 🧑‍🤝‍🧑 community, 🐌 idle, redesign, browser-compat
