### ISSUE TITLE
'Looking to become a front-end web developer?' container and "Get started" button 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1731] opened 2020-11-13 14:18 UTC
1. This section is found on many MDN pages. 
https://developer.allizom.org/en-US/docs/Web/JavaScript
https://developer.allizom.org/en-US/docs/Learn/JavaScript/First_steps
https://developer.allizom.org/en-US/docs/Learn/JavaScript/Building_blocks
https://developer.allizom.org/en-US/docs/Learn/HTML/Introduction_to_HTML
https://developer.allizom.org/en-US/docs/Web/CSS

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/99080145-8aaa4180-25c9-11eb-80c8-032d382624c8.png)

**Expected result:**
The whole message would look better if the container would be highlighted in a darker color to bring all the elements together. 
The "Get started" button should also be styled to look similar to production or the "Previous and "Next" buttons from the Javascript basics pages. 
https://developer.allizom.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics
![image](https://user-images.githubusercontent.com/53306802/99080560-22a82b00-25ca-11eb-9f16-5de12fb94d7e.png)

**Comment by schalkneethling** [comment] 2020-11-13 14:40
Thanks, @mirunacurtean, this is a duplicate of https://github.com/mdn/yari/issues/1606

**Closed by schalkneethling** 2020-11-13 14:40 UTC

**Comment by mirunacurtean** [comment] 2020-11-13 15:26
Ah, sorry @schalkneethling. Should have looked closer at what was logged.

**Comment by schalkneethling** [comment] 2020-11-14 06:18
> Ah, sorry @schalkneethling. Should have looked closer at what was logged.

No worries, thank you for all your testing efforts 🍵
