### ISSUE TITLE
Last modified is in see also

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1923] opened 2020-12-03 18:24 UTC
Seems in the see also section.
Anyway Is a single bullet list...

![Screenshot_20201203-192226.png](https://user-images.githubusercontent.com/44380480/101071597-1e55a900-359d-11eb-8c3d-b9c85f89f2d2.png)

**Comment by peterbe** [comment] 2020-12-03 19:11
Duplicate of https://github.com/mdn/yari/issues/1613

**Closed by peterbe** 2020-12-03 19:11 UTC
