### ISSUE TITLE
Sidebar loses context

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#5395] opened 2022-03-02 07:55 UTC
When you click on a sidebar link it opens at the top of the new page. For long pages, this means you have lost context:
1. The page you clicked is below the fold - e.g. https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started
2. There is no way to find that page, because it isn't **highlighted** in the sidebar at all.

Traditionally these problems are solved by the sidebar opening the tree to the current page, collapsing everything else, scrolling to the link on sidebar if it is off page, and highlighting it (in a different colour or boldness).

**Comment by caugner** [comment] 2022-03-11 15:25
Duplicate of #5547

**Closed by caugner** 2022-03-11 15:25 UTC
Labels: redesign, sidebar
