### ISSUE TITLE
Enhancement to new mdn docs 

### ISSUE THREAD

**Issue by ganeshmarathe** [mdn/yari#5681] opened 2022-03-19 08:04 UTC
### Summary

Improvement request: Introduce hide/show option for left side table of contents for any topic. 

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API

### Reproduction steps

1.Go to above url or any topic in mdn docs
2. There is no option to hide table of contents on left
3.You can see **https://angular.io/docs** for how it it done.I am attaching screenshot of the same here as well.
Congrats for making new site which is very good in my opinion. [Dark mode is super cool]

### Expected behavior

We should be able to hide table of contents for better screen usability.
I am attaching angular docs site as a reference for improvement

### Actual behavior

No option available at the moment to hide table of contents

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Screenshot

![Screenshot_Docs](https://user-images.githubusercontent.com/31573206/159113016-87dc45a2-1d73-44f8-9629-d6bda8bec7ed.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment] 2022-09-14 16:42
Duplicate of #5421.

**Closed by caugner** 2022-09-14 16:42 UTC
Labels: 🐛 bug, 🐌 idle, needs-triage
