### ISSUE TITLE
Bug: Media Source Extensions API crashes due to yari JavaScript - No browser compatability

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/yari#5551] opened 2022-03-09 14:57 UTC
# Summary

https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API infinitely logs in the console `t.releases is undefined`, and if you open the JavaScript console the page quickly crashes. No browser compatibility appears on that page, and a statement says: "[MediaSource interface](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API#mediasource_interface) Unfortunately, this table has encountered unhandled error and the content cannot be shown."

## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [ ] Chrome: (what version?)
- [x] Firefox: 97
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [ ] Windows: (what version?)
- [ ] Mac OS: (what version?)
- [x] Linux: Fedora 34

**Comment by danielhjacobs** [comment] 2022-03-09 15:09
So the error comes from https://github.com/mdn/yari/blob/b70f28c747be0cffc71f260a90480114a1221d15/client/src/document/ingredients/browser-compatibility-table/utils.ts#L57.

**Comment by danielhjacobs** [comment] 2022-03-09 15:43
Weird: This does only affect the official MDN documentation.

This is the official documentation:
![Screenshot from 2022-03-09 10-43-04](https://user-images.githubusercontent.com/29206584/157476382-7e66d13f-04d3-4a3a-b493-013684aa0bdd.png)

This is localhost:
![Screenshot from 2022-03-09 10-43-45](https://user-images.githubusercontent.com/29206584/157476505-56d73fad-d0fe-4a35-b2cd-29f57dbece84.png)

**Comment by caugner** [comment] 2022-03-09 19:43
Thanks for all the additional details!

I believe this is a duplicate of #5531 and has already been fixed in #5529, which has meanwhile been deployed.

And indeed, if I check https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API#browser_compatibility, everything looks fine.

**Closed by caugner** 2022-03-09 19:43 UTC
Labels: needs-triage, browser-compat
