### ISSUE TITLE
500 error: “Error: Unable to figure out locale from . with .” for Web/API/DirectoryReaderSync locally

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#3515] opened 2021-04-14 08:34 UTC
When I navigate to http://localhost:5000/en-US/docs/Web/API/DirectoryReaderSync locally, I get this:
```
Error: Unable to figure out locale from . with .
```
But I don’t get any error with https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform-origin

Stack trace:
```
Injecting flaws into /Users/mike/workspace/mdn/content/files/en-us/web/api/directoryreadersync/index.html (/en-US/docs/Web/API/DirectoryReaderSync) failed.
Error in buildDocumentFromURL(/en-us/docs/web/api/directoryreadersync) Error: Unable to figure out locale from . with .
    at extractLocale (/Users/mike/workspace/mdn/yari/content/document.js:65:11)
    at /Users/mike/workspace/mdn/yari/content/document.js:263:18
    at Object.findByURL (/Users/mike/workspace/mdn/yari/content/document.js:393:15)
    at Node.<anonymous> (/Users/mike/workspace/mdn/yari/build/flaws.js:315:30)
    at initialize.exports.each (/Users/mike/workspace/mdn/yari/node_modules/cheerio/lib/api/traversing.js:562:24)
    at injectBrokenLinksFlaws (/Users/mike/workspace/mdn/yari/build/flaws.js:282:16)
    at injectFlaws (/Users/mike/workspace/mdn/yari/build/flaws.js:58:5)
    at buildDocument (/Users/mike/workspace/mdn/yari/build/index.js:383:5)
    at async buildDocumentFromURL (/Users/mike/workspace/mdn/yari/server/index.js:53:10)
    at async /Users/mike/workspace/mdn/yari/server/index.js:234:19
```

**Comment by peterbe** [comment] 2021-04-14 19:31
I'm unable to reproduce. I tried from the mdn/content repo and from the mdn/yari repo.

**Comment by sideshowbarker** [comment] 2021-04-14 19:54
> I'm unable to reproduce. I tried from the mdn/content repo and from the mdn/yari repo.

I get it both from the mdn/content repo and from the mdn/yari repo — so I guess that must mean there must be some difference in my local environment. But I don’t know what it could be. I’m on macOS

FWIW, here’s the stack trace I get from the mdn/content repo —

```
Injecting flaws into /Users/mike/workspace/mdn/content/files/en-us/web/api/directoryreadersync/index.html (/en-US/docs/Web/API/DirectoryReaderSync) failed.
Error in buildDocumentFromURL(/en-us/docs/web/api/directoryreadersync) Error: Unable to figure out locale from . with .
    at extractLocale (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:65:11)
    at /Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:263:18
    at Object.findByURL (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:393:15)
    at Node.<anonymous> (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/flaws.js:315:30)
    at initialize.exports.each (/Users/mike/workspace/mdn/content/node_modules/cheerio/lib/api/traversing.js:547:24)
    at injectBrokenLinksFlaws (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/flaws.js:282:16)
    at injectFlaws (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/flaws.js:58:5)
    at buildDocument (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/index.js:383:5)
    at async buildDocumentFromURL (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/server/index.js:53:10)
    at async /Users/mike/workspace/mdn/content/node_modules/@mdn/yari/server/index.js:234:19
```

**Comment by sideshowbarker** [comment] 2021-04-14 20:22
OK, stepping through it, I find the specific place where it’s failing is here:

https://github.com/mdn/content/blob/master/files/en-us/web/api/directoryreadersync/index.html#L24

```html
<p>Before you call the only method in this interface, <a href="/#readEntries()" title="#readEntries()"><code>readEntries()</code></a>, create the <a href="/en-US/docs/Web/API/DirectoryEntrySync"><code>DirectoryEntrySync</code></a> object. But DirectoryEntrySync (as well as <a href="/en-US/docs/Web/API/FileEntrySync">FileEntrySync</a>) is not a data type that you can pass between a calling app and Web Worker thread. It's not a big deal, because you don't really need to have the main app and the worker thread see the same JavaScript object; you just need them to access the same files. You can do that by passing a list of  <code>filesystem:</code> URLs—which are just strings—instead of a list of entries. You can also use the <code>filesystem:</code> URL to look up the entry with <a href="/en-US/docs/Web/API/LocalFileSystem#resolvelocalfilesystemurl()"><code>resolveLocalFileSystemURL()</code></a>. That gets you back to a DirectoryEntrySync (as well as FileEntrySync) object.</p>
```
That `href="/#readEntries()"` is the cause.

If I change that to `href="#readEntries()"` — that is, drop the leading `/` — then everything works as expected and the failure and 500 error no longer occur.

So the leading `/` in that URL seems to be the root cause.

Why I would be hitting a problem with that in my environment but you wouldn’t be, I dunno…

**Comment by peterbe** [comment] 2021-04-14 21:13
That explanation makes a lot of sense. 
What doesn't make sense is; how come it's not happening on my macOS?!? So it's me being weird :)
I'll know what to look for now hopefully.

**Comment by peterbe** [comment] 2021-04-14 21:39
What it could be is that your `@mdn/yari` inside `node_modules` is too old. Your stacktrace talks about `@mdn/yari/build/flaws.js:315:30` and that looks like the call of `const found = Document.findByURL(hrefNormalized);` which in today's `main` of Yari is down on line 346. 

Perhaps check that you have the latest version of `main` for mdn/content next time you run `yarn install`. 

To debug this, you can download https://gist.github.com/peterbe/b5d2cca5d5ed9eb82efd74d42e256aa8 into your mdn/content repo and then type:

```
▶ CONTENT_ROOT=files node dummy.js
undefined
```
it should not crash if you have the latest `@mdn/yari` installed.

**Comment by sideshowbarker** [comment] 2021-04-15 01:05
> Perhaps check that you have the latest version of `main` for mdn/content next time you run `yarn install`.

OK, I just ran this:

```
$ curl -s -O https://gist.githubusercontent.com/peterbe/b5d2cca5d5ed9eb82efd74d42e256aa8/raw/a2d0799f5de950cabaa5ceffa7eebb3ac8fb58ee/dummy.js \
    && git pull \
    && yarn install \
    && CONTENT_ROOT=/Users/mike/workspace/mdn/content/files node dummy.js

Already up to date.
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.33s.
/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:65
    throw new Error(
    ^

Error: Unable to figure out locale from . with .
    at extractLocale (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:65:11)
    at /Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:263:18
    at Object.findByURL (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:393:15)
    at Object.<anonymous> (/Users/mike/workspace/mdn/content/dummy.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

So I guess that must mean I still don’t have the latest version of `main`?

If so, how else other than doing `git pull && yarn install` can I ensure it gets updated?

**Comment by peterbe** [comment] 2021-04-15 09:50
git pull is a shortcut for 'git pull origin main'. 
Could it be that origin is your fork and not the mdn one?

**Comment by sideshowbarker** [comment] 2021-04-15 13:22
>  Could it be that origin is your fork and not the mdn one?

No, it’s definitely not that at least —

```
mike@Darwin ~/workspace/mdn/content (main)
$ git remote get-url origin
git@github.com:mdn/content.git

mike@Darwin ~/workspace/mdn/content (main)
$ git symbolic-ref refs/remotes/origin/HEAD
refs/remotes/origin/main
```

**Comment by sideshowbarker** [comment] 2021-04-15 13:36
> What it could be is that your `@mdn/yari` inside `node_modules` is too old. Your stacktrace talks about `@mdn/yari/build/flaws.js:315:30` and that looks like the call of `const found = Document.findByURL(hrefNormalized);` which in today's `main` of Yari is down on line 346.

`Document.findByURL(hrefNormalized)` is on line 345 in my current `flaws.js`. The surrounding lines looks like this:

```
  339       const hrefSplit = href.split("#");
  340       let hrefNormalized = hrefSplit[0];
  341       if (hrefNormalized.startsWith("/docs/")) {
  342         const thisDocumentLocale = doc.mdn_url.split("/")[1];
  343         hrefNormalized = `/${thisDocumentLocale}${hrefNormalized}`;
  344       }
  345       const found = Document.findByURL(hrefNormalized);
```
The stack trace with the current line numbers looks like this:

```
Injecting flaws into /Users/mike/workspace/mdn/content/files/en-us/web/api/directoryreadersync/index.html (/en-US/docs/Web/API/DirectoryReaderSync) failed.
Error in buildDocumentFromURL(/en-us/docs/web/api/directoryreadersync) Error: Unable to figure out locale from . with .
    at extractLocale (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:65:11)
    at /Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:263:18
    at Object.findByURL (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:393:15)
    at Node.<anonymous> (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/flaws.js:345:30)
    at initialize.exports.each (/Users/mike/workspace/mdn/content/node_modules/cheerio/lib/api/traversing.js:547:24)
    at injectBrokenLinksFlaws (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/flaws.js:297:16)
    at injectFlaws (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/flaws.js:58:5)
    at buildDocument (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/build/index.js:398:5)
    at async buildDocumentFromURL (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/server/index.js:53:10)
    at async /Users/mike/workspace/mdn/content/node_modules/@mdn/yari/server/index.js:234:19
buildDocumentFromURL(/en-us/docs/web/api/directoryreadersync): 259.013ms
```

**Comment by peterbe** [comment] 2021-04-15 14:29
Wow this is getting tricky and fun at the same time. 

I don't know if this is the explanation but I can kinda simulate your same exact error if I create a `index.html` in the root of that `$CONTENT_ROOT` env var. I.e.

```
▶ node dummy.js
/Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:65
    throw new Error(
    ^

Error: Unable to figure out locale from . with .
    at extractLocale (/Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:65:11)
    at /Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:265:18
    at Object.findByURL (/Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:397:15)
    at Object.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/dummy.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

```

So do you have a `index.html` file in the root of the CONTENT_ROOT?

**Comment by peterbe** [comment] 2021-04-15 14:32
By the way, it has nothing to do with the `#readEntries()` part. You can get the same error, if the `index.html` file exists in the root, and you do `Document.findByURL('/')`. 

I think it's a mistake to even allow it to get that far. `Document.findByURL('/')` doesn't make sense and kinda breaks the API and it should throw. Then we should, at a higher level, do whatever we need to to prevent this even being attempted.

**Comment by peterbe** [comment] 2021-04-15 14:36
Actually, just to make things extra complicated. The flaw checker shouldn't have even attempted to look up `/#readentries()` as a possible URL. It should be smart to see that `/` is the home page so it should treat that differently. 
In fact, we deliberately treat broken link lookups for `/` and `/en-US` or `/fr/` differently, as of this recently landed PR: https://github.com/mdn/yari/pull/3507
But I wonder if it incorrectly gets "bypassed" since `'/' !== '/#stuff'`. 
So I'll take a look at that.

**Comment by sideshowbarker** [comment] 2021-04-15 14:45
> So do you have a `index.html` file in the root of the CONTENT_ROOT?

Interesting —

```
mike@Darwin ~/workspace/mdn/content (main)
$ ls
total 632
-rw-r--r--    1 mike   492B Dec 12 12:48 CODE_OF_CONDUCT.md
-rw-r--r--    1 mike    23K Feb 24 15:19 LICENSE.md
-rw-r--r--    1 mike    35K Apr  7 09:38 README.md
-rw-r--r--    1 mike    29K Jan  6 08:37 README.md~
-rw-r--r--    1 mike    12K Apr  7 09:38 REVIEWING.md
drwxr-xr-x    4 mike   128B Mar 16 16:34 files
drwxr-xr-x    2 mike    64B Jan 18 10:48 index.html
drwxr-xr-x  527 mike    16K Apr 15 22:25 node_modules
-rw-r--r--    1 mike   829B Apr 15 21:19 package.json
drwxr-xr-x    5 mike   160B Mar 16 16:34 pr-lint
drwxr-xr-x    6 mike   192B Apr 13 21:11 rfcs
drwxr-xr-x    3 mike    96B Mar 16 16:34 scripts
-rw-r--r--    1 mike   198K Apr 15 21:19 yarn.lock
```
That `index.html` was a *directory*. I have absolutely no idea where it came from, but I guess it was probably from some command I mistyped some time back (Jan 18, apparently).

But I just now removed the directory, but I’m still getting the same failure:

```
$ ls 
    && curl -s -O https://gist.githubusercontent.com/peterbe/b5d2cca5d5ed9eb82efd74d42e256aa8/raw/a2d0799f5de950cabaa5ceffa7eebb3ac8fb58ee/dummy.js
    && git pull
    && yarn install
    && CONTENT_ROOT=/Users/mike/workspace/mdn/content/files node dummy.js

total 568
-rw-r--r--    1 mike   492B Dec 12 12:48 CODE_OF_CONDUCT.md
-rw-r--r--    1 mike    23K Feb 24 15:19 LICENSE.md
-rw-r--r--    1 mike    35K Apr  7 09:38 README.md
-rw-r--r--    1 mike    12K Apr  7 09:38 REVIEWING.md
drwxr-xr-x    4 mike   128B Mar 16 16:34 files
drwxr-xr-x  527 mike    16K Apr 15 22:25 node_modules
-rw-r--r--    1 mike   829B Apr 15 21:19 package.json
drwxr-xr-x    5 mike   160B Mar 16 16:34 pr-lint
drwxr-xr-x    6 mike   192B Apr 13 21:11 rfcs
drwxr-xr-x    3 mike    96B Mar 16 16:34 scripts
-rw-r--r--    1 mike   198K Apr 15 21:19 yarn.lock
Already up to date.
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.38s.
/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:65
    throw new Error(
    ^

Error: Unable to figure out locale from . with .
    at extractLocale (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:65:11)
    at /Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:263:18
    at Object.findByURL (/Users/mike/workspace/mdn/content/node_modules/@mdn/yari/content/document.js:393:15)
    at Object.<anonymous> (/Users/mike/workspace/mdn/content/dummy.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by peterbe** [comment] 2021-04-15 15:06
What about `ls /Users/mike/workspace/mdn/content/files` I.e. one level deeper.

**Comment by sideshowbarker** [comment] 2021-04-15 17:07
> What about `ls /Users/mike/workspace/mdn/content/files` I.e. one level deeper.

```
$ ls /Users/mike/workspace/mdn/content/files
total 2888
drwxr-xr-x  17 mike   544B Apr 15 23:38 en-us
-rw-r--r--   1 mike   1.4M Mar 16 16:34 popularities.json
```
But anyway, I’ve found that I can even reproduce this in a fresh clone from scratch:
```
$ cd /tmp && git clone -q git@github.com:mdn/content.git && cd content \
    && curl -s -O https://gist.githubusercontent.com/peterbe/b5d2cca5d5ed9eb82efd74d42e256aa8/raw/a2d0799f5de950cabaa5ceffa7eebb3ac8fb58ee/dummy.js
    && git pull && yarn install && CONTENT_ROOT=/tmp/content/files node dummy.js

Already up to date.
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
✨  Done in 6.19s.
/private/tmp/content/node_modules/@mdn/yari/content/document.js:65
    throw new Error(
    ^

Error: Unable to figure out locale from . with .
    at extractLocale (/private/tmp/content/node_modules/@mdn/yari/content/document.js:65:11)
    at /private/tmp/content/node_modules/@mdn/yari/content/document.js:263:18
    at Object.findByURL (/private/tmp/content/node_modules/@mdn/yari/content/document.js:393:15)
    at Object.<anonymous> (/private/tmp/content/dummy.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by peterbe** [comment] 2021-04-15 17:09
Can you test switching to the branch in https://github.com/mdn/yari/pull/3528 and see what happens?

**Comment by sideshowbarker** [comment] 2021-04-15 21:34
> Can you test switching to the branch in #3528 and see what happens?

OK, yep, I can confirm that I no longer see the problem when I test with the code from that `peterbe-3515-dont-broken_links-check-home-page-urls-with-hash` branch, but if I switch back to `main`, the problem reappears.

So I guess that means whatever part of the source that #3528 change is touching must be the code causing the problem.

**Closed** 2021-04-16 14:15 UTC

**Comment by peterbe** [comment] 2021-04-16 16:21
I'm only partially interested in continuing to debug this. :)
The reason is that prior to [the fix](https://github.com/mdn/yari/commit/d936896f70b5cdf217e1f20f265e4e5c949c4e1f) the code would get itself into doing things that don't make sense? Like asking a chair if it speaks French or Greek. 
It caused a lookup for `Document.findByURL('/')` which would never make sense because as part of the `findByURL()` code, it assumed that the input string would always be of the nature `/$LOCALE/docs/$SLUG` but we broke that assumption and things went, clearly, sideways. Now, there's code that prevents it from even going that far. Basically, if you use `findByURL('anystring that doesn't contain /docs/ here')` would quickly just `return undefined` so it could even attempt to try to figure out which locale the found document was belonging to. 

I hope this'll make your unlucky situation be a thing of the past.

**Comment by sideshowbarker** [comment] 2021-04-17 02:58
> I'm only partially interested in continuing to debug this. :)

Yeah, as long as the immediate problem is no longer occurring, I’m happy :) But I do remain curious about what underlying difference made it occur for me and not for you.

**Comment by peterbe** [comment] 2021-04-19 13:43
> But I do remain curious about what underlying difference made it occur for me and not for you.

Me too! 
Perhaps you can go back to the git SHA of main before it got fixed and put in a couple of `console.log()` to find out which URLs were sent to `findByURL()` that was causing it.
