### ISSUE TITLE
UI bug 

### ISSUE THREAD

**Issue by vaibhavugale** [mdn/yari#8496] opened 2023-03-25 16:21 UTC
Following URl Have UI issue

url--> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup
![Screenshot (37)](https://user-images.githubusercontent.com/102985212/227729335-961f85b5-654f-4304-8e89-5eadb2642c8d.png)

**Comment by teoli2003** [comment] 2023-03-25 16:24
Duplicate of mdn/yari#8494

**Comment by caugner** [comment] 2023-03-27 09:58
If you're experiencing a different problem than the one described in https://github.com/mdn/yari/issues/8494, please open a new issue using our [bug report template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml). 🙏

**Closed by caugner** 2023-03-27 09:58 UTC
Labels: needs triage
