### ISSUE TITLE
<pre> should be easily copied

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1810] opened 2020-11-21 10:12 UTC
### Icon in bottom right on hover

![image](https://user-images.githubusercontent.com/44380480/99874653-061f7a80-2bea-11eb-81ca-ca0b27e08d39.png)

### Icon visibile in top right
![Screenshot_20201125-054659](https://user-images.githubusercontent.com/44380480/100184453-d3270080-2ee1-11eb-8290-88c9539bb8cd.png)

#### The snippet written in JavaScript

```javascript

function f(){}
```
📋

## Resourses
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by peterbe** [comment] 2020-12-02 20:44
Duplicate of https://github.com/mdn/yari/issues/82

**Closed by peterbe** 2020-12-02 20:44 UTC
