### ISSUE TITLE
mailto and tel hrefs are blocked by chrome cors policy

### ISSUE THREAD

**Issue by raymonddinh** [mdn/yari#7908] opened 2023-01-04 03:46 UTC
### Summary

When pressing any mailto and tel hrefs, it is blocked by cors when using chrome. Trying to press on the email in the try it section leads to that iframe dying saying the content is blocked.

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### Reproduction steps

1. Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address
2. Press the jim@rock.com email in the try it section
3. In the console you should the following error should be logged:
`Refused to frame '' because it violates the following Content Security Policy directive: "frame-src 'self' interactive-examples.mdn.mozilla.net interactive-examples.prod.mdn.mozilla.net interactive-examples.stage.mdn.mozilla.net mdn.github.io yari-demos.prod.mdn.mozit.cloud mdn.mozillademos.org yari-demos.stage.mdn.mozit.cloud jsfiddle.net www.youtube-nocookie.com codepen.io survey.alchemer.com".`

### Expected behavior

Opens an email client where you can email jim@rock.com

### Actual behavior

The action is blocked and the iframe turns to into the attached image.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/74843220/210480561-40feffab-b245-4e17-aca0-093c345ea860.png)

### Anything else?

Seems to be only Chrome, Firefox and Safari seem to be working okay.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by danielhjacobs** [comment] 2023-01-05 16:11
I believe this can be fixed by adding `target="_top"` to https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/content-sectioning/address.html and https://github.com/mdn/interactive-examples/blob/main/live-examples/html-examples/inline-text-semantics/a.html.

**Comment by LeoMcA** [comment] 2023-03-02 16:43
Can't reproduce, perhaps Chrome released an update with a fix. Please comment if the issue still affects you on the latest Chrome version.

**Closed by LeoMcA** 2023-03-02 16:43 UTC
Labels: needs-triage
