### ISSUE TITLE
Hydration errors reported in the console

### ISSUE THREAD

**Issue by mattbrannon** [mdn/yari#6764] opened 2022-07-25 03:06 UTC
If you go to [this page](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming) and open the console you'll see some errors reported by React. I've noticed it happens on some other pages as well but it doesn't happen on every page.

Specifically these are the errors reported:

https://reactjs.org/docs/error-decoder.html/?invariant=425
https://reactjs.org/docs/error-decoder.html/?invariant=418
https://reactjs.org/docs/error-decoder.html/?invariant=423

![Screen Shot 2022-07-24 at 9 38 29 PM](https://user-images.githubusercontent.com/36570183/180686271-c41b8d9c-1fd3-4427-941b-3d5d7cc0c868.png)

**Comment by caugner** [comment] 2022-08-18 19:12
I don't see those errors (anymore?) on that page.

@mattbrannon Could you please check if this might have been resolved?

**Comment by mattbrannon** [comment] 2022-08-19 04:29
@caugner I just checked again and I'm still seeing the same thing. 
![Screen Shot 2022-08-18 at 11 27 49 PM](https://user-images.githubusercontent.com/36570183/185543056-acdbfd3e-7651-4df7-ab66-55fe7b34a9ee.png)

**Comment by caugner** [comment] 2022-08-19 09:29
@mattbrannon These look like warnings we have fixed some weeks ago.

1. Do you have MDN Offline enabled - but not recently updated - by any chance?
2. Do you see the same warnings on https://developer.allizom.org/en-US/docs/Web/API/PerformanceNavigationTiming?
3. What operating system / browser / browser version are you using?

**Comment by mattbrannon** [comment] 2022-08-20 07:19
> 1\. Do you have MDN Offline enabled - but not recently updated - by any chance?

I don't have MDN Offline enabled.

> 2\. Do you see the same warnings on https://developer.allizom.org/en-US/docs/Web/API/PerformanceNavigationTiming?

Yes, the same error occurs at both URLs.

> 3\. What operating system / browser / browser version are you using?

I'm on MacOS 10.14.6.
For the sake of completeness I tried multiple browsers. The error occurred in every browser I tested. 

Tested with
 - Chrome: 104.0.5112.101
 - Firefox: 103.0.2
 - Edge: 104.0.1293.63
 - Safari: 14.1.2 (14611.3.10.1.7)

**Comment by caugner** [comment] 2022-08-22 11:32
I have tried again (Mac OS 12.5.1), but still couldn't reproduce in these browsers:

- Chrome 104.0.5112.101
- Edge 104.0.1293.63
- Firefox 103.0.2
- Safari 15.6.1

@LeoMcA (different locale/timezone) was also unable to reproduce those errors, so for now I will close this issue as "can't repro".

Rest assured that those errors are not severe, i.e. they don't impair your experience on the site. 😉 

Don't hesitate to comment any additional findings around reproducing or resolving those errors. If you're curious, you could [build and run yari locally](https://github.com/mdn/yari#quickstart) and check if you're seeing the errors at http://localhost:5042/en-US/docs/Web/API/PerformanceNavigationTiming).

**Closed by caugner** 2022-08-22 11:32 UTC
Labels: need more info

**Comment by mattbrannon** [comment] 2022-08-22 11:36
@caugner Strange that you're not seeing it. Maybe something on my end but I don't see how that could be. Anyways, yeah no worries. I just saw the error in the console and thought it would be worth letting people know about it.
