### ISSUE TITLE
In the "Site search" box, on Firefox, the Home and End keys do nothing

### ISSUE THREAD

**Issue by ifyousayso** [mdn/yari#5239] opened 2022-02-04 08:39 UTC
I type a word (function name) that is common and realize that I have to be more specific. Trying to use the Home key to get to the beginning of the word does nothing (it's disabled?). CTRL + A works to select all and retype everything, but why no Home/End?

**Comment by schalkneethling** [comment] 2022-04-18 21:14
> I type a word (function name) that is common and realize that I have to be more specific. Trying to use the Home key to get to the beginning of the word does nothing (it's disabled?). CTRL + A works to select all and retype everything, but why no Home/End?

Hey there, do you still find this to be the case?

**Comment by ifyousayso** [comment] 2022-04-18 22:15
Okay, so I just tested this again and it's exactly the same.

However, now I also noticed that when I start typing something, a suggestion/result box shows up. I happened to have the mouse cursor hovering the first result. Using Home and End goes to the first and last search results in that box rather than move the keyboard cursor to the beginning and end of the word that I am typing.

So I guess that my issue is that functional keyboard keys were hooked and used for other purposes than controlling the cursor in the text box, and when the mouse happens to hover the first result (it's highlighted), it really seems like Home does nothing at all.

**Comment by schalkneethling** [comment] 2022-04-26 10:42
Thank you for your additional feedback @usename. The issue has been marked as `needs-triage`. The engineering team will review and prioritize this issue.

**Comment by JobLeonard** [comment] 2022-05-23 15:25
I just discovered that the <kbd>Home</kbd> and <kbd>End</kbd> keys now change which of the autocomplete suggestions are selected (the top or the bottom one, respectively).

This is neither what I expect nor what I want, and also kind of feels like messing with accessibility in a way.

**Comment by JobLeonard** [comment] 2022-05-24 14:58
Thank you for looking into it so quickly!

**Comment by caugner** [comment] 2022-09-15 17:32
Duplicate of https://github.com/mdn/yari/issues/6466.

> Please note that we're using [Downshift.js](https://github.com/downshift-js/downshift) and their [Combobox](https://www.downshift-js.com/use-combobox/) implementation for the search suggestions, and we haven't customized their [default event handlers](https://github.com/downshift-js/downshift/tree/1c7698080805e05f5180dd223cbc17932a85fd42/src/hooks/useCombobox#event-handlers), nor do we plan to do so.
> 
> However, you should be able to use `Ctrl+LeftArrow` and `Ctrl+RightArrow` to go to the start / end of the input value. 😉

**Closed by caugner** 2022-09-15 17:32 UTC
Labels: p1, ux, 🧑‍🤝‍🧑 community, needs-triage
