### ISSUE TITLE
The platform doesn't seem to remember my language preference

### ISSUE THREAD

**Issue by asterix123** [mdn/yari#2724] opened 2021-01-28 16:07 UTC
I live in Ukraine and a while ago Google started to 'promote' search results in Russian language over search results in English. Even when you search in English :) So whenever I come to MDN from Google, I almost always see a page in Russian, instead of seeing the page in English (as expected). 

Therefore, I was wondering if it would be possible to save language preference in my profile and be redirected to English version of the page, even when I visit MDN links containing /ru/ in the URL?

**Comment by peterbe** [comment] 2021-01-28 17:35
Excellent question! And you're not the first one to bring it up. There are some browser extensions that you might be able to use. But MDN is a static site so it's a bit hard to do the redirecting. Another challenge is that we still have URLs that are different from the English URL (so it wouldn't simply be a matter of swapping from `/ru/` to `/en-US/`). But we're working actively on that (hi @fiji-flo ) so it can become easier in a couple of weeks. 

One option we could do is that if you do stumble into a page whose locale is different from your cookie, a little banner appears. And in that banner there's a link to the English URL and an option/button that enables it to auto-redirect next time.

**Comment by asterix123** [comment] 2021-01-29 12:34
@peterbe Thank you for a detailed reply. Yes, a banner could be a nice solution.

**Comment by peterbe** [comment] 2021-01-29 13:21
I think we should keep it open. That way it helps us remember how many people are asking about this.

**Comment by mattiapontonio** [comment] 2021-01-29 13:27
Does It help?
https://blog.mozilla.org/l10n/2019/04/02/changing-the-language-of-firefox-directly-from-the-browser/

**Comment by peterbe** [comment] 2021-01-29 13:30
> Does It help?
> https://blog.mozilla.org/l10n/2019/04/02/changing-the-language-of-firefox-directly-from-the-browser/

The problem is that we have the locale hardcoded in the URL. That gets indexed by Google and Google presents those links. MDN does neat things with the browser's request (cookies and/or `Accept-Language` header) but *only* if the locale isn't already in the URL.

**Comment by schalkneethling** [comment] 2021-03-31 17:36
@peterbe will this be addressed by the new `settings` page?

**Comment by escattone** [comment] 2021-03-31 23:33
@schalkneethling No, that still uses the `preferredlocale` cookie, which is only respected for URL's without a locale, but we've added this feature request to our 2021 backlog.

**Comment by schalkneethling** [comment] 2021-04-01 04:07
> @schalkneethling No, that still uses the `preferredlocale` cookie, which is only respected for URL's without a locale, but we've added this feature request to our 2021 backlog.

Aha, gotcha! Now I understand that better as well. Thanks, Ryan

**Closed** 2024-09-25 11:08 UTC
Labels: enhancement, localization, p2, ux, 🐌 idle, idle, effort: medium
