### ISSUE TITLE
Spanish language option breaks navigation 

### ISSUE THREAD

**Issue by pablospanish9** [mdn/yari#5172] opened 2022-01-16 20:38 UTC
When I clicked on the Spanish option, your website translated it OK for that page. When I tried to navigate back to the English, the Spanish option was automatically tagged to your webpage and most navigation was broken. I could not freely navigate without this Spanish designation, which I did not want anymore, and most pages were not found.

https://developer.mozilla.org/es/docs/Web/Reference

**Comment by schalkneethling** [comment] 2022-01-18 16:54
Thank you for reporting, @pablospanish9. Quick question, if you for example go to https://developer.mozilla.org/en-US/docs/Web/JavaScript, then click on "Change language" and choose Español. The page will reload as `es`. Now, if you navigate around all is generally good i.e. it keeps the `es` locale?

If you now click on "Change language" again and choose "English US" the page reloads with `en-US` and navigating around keeps you in `en-US`?

> When I tried to navigate back to the English

Did you use the "View in English" link?

**Comment by pablospanish9** [comment] 2022-01-18 17:56
Yes. It keeps the es language and it seems to be working OK with all other pages. It stays in es. And I can click the English and it stays in English. I emailed the link to the one page where I received the error. It is possible that the behavior is limited to that one page.

**Comment by schalkneethling** [comment] 2022-01-19 09:21
> It is possible that the behavior is limited to that one page.

Highly unlikely as they all use the same code logic. I think it may be that, that page really does not exist for `es` still. The `es` locale became a top-level locale in the last couple of days and so I suspect this will be resolved soon. If you want to bring this issue to their attention, please have a look at https://github.com/mdn/translated-content/

From you last description it sounds like things work as intended so, I am going to go ahead and close this issue for now. Thank you again for reporting and providing feedback.

**Closed by schalkneethling** 2022-01-19 09:21 UTC
Labels: bug, p1, platform
