### ISSUE TITLE
Add SERP Yellow label for GitHub

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2131] opened 2020-12-14 15:59 UTC

**Comment by peterbe** [comment] 2020-12-15 19:15
Please explain or close.

**Comment by mattiapontonio** [comment] 2020-12-15 19:50
This is a issue for GitHub.
Should be good to add a label (and use It) regarding the SERP and the Search that Is a kind of milestone.

**Comment by peterbe** [comment] 2020-12-15 22:01
What do you mean "for GitHub"?
Can you explain this so that anybody can understand? Are we talking about a bug or a feature request? Perhaps take screenshots and quotes from links to external resources. And please include a section about **why** this issue is valuable or important or relevant. What do we stand to gain and how much? What are the disadvantages?  

Please remember that reading and triaging filed issues costs time. It's a distraction and we read every issue. But if we can't understand what the point is, it causes a distracting time waste. If the issue isn't of any quality, we have to close it.

**Comment by mattiapontonio** [comment] 2020-12-16 21:16
![Screenshot_20201216-004810.png](https://user-images.githubusercontent.com/44380480/102407243-10b41080-3fec-11eb-9b69-170fb16f3ac9.png)

I was talking about adding a label in GitHub. 

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/managing-labels

**Closed** 2020-12-16 21:16 UTC
