### ISSUE TITLE
Links with fragments don't work well always

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2665] opened 2021-01-24 01:15 UTC
![ezgif-6-07de31de6386.gif](https://user-images.githubusercontent.com/44380480/105754084-ed18aa00-5f49-11eb-99f2-bdc1e4a89ec3.gif)

---
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast#examples

- Sometimes You see a Little flash of the footer
- Sometimes You see the footer and not the fragment

---

https://whatismybrowser.com/w/8YGSD4J

**Comment by Ryuno-Ki** [comment] 2021-01-24 09:47
It would be easier to replicate if you would share the link you loaded (you seem to come from a Google search. Or is it a GitHub issue?).

By „examples” you are referring to a FOIT? (Flash of invisible text)
The scroll bar is the vertical one? (Is that restricted to this one page? I believe, it's an OS feature on your mobile. Which one do you use?).
Or are you referring to the horizontal one of the code block? Can you still scroll it?

I can't make sense of the last bullet item.

**Comment by mattiapontonio** [comment] 2021-01-24 12:18
The MAIN problem not catched in the GIF Is that sometimes when You visit a URL with a framgment t'ha Page load but the scrollto the fragment don't work. You see the footer instead.
Is the fragment present in the first HTML? 

Lemme try curl.

**Comment by Ryuno-Ki** [comment] 2021-01-24 13:37
> You visit a URL with a framgment t'ha Page load but the scrollto the fragment don't work. You see the footer instead.

In my experience, this is caused by asychronously loaded content.
The browser tries to keep the content you visited in the viewport.
Thanks to the ad industry (not related in this case), there have been instances, where large elements were injected and displayed before that content. Thus, the content was pushed down, which led to frustration on the user's end.

So if you visit a page built with SPAs (for example), there is this „app shell” which only contains minimum HTML. Chances are, you're seeing `<header>` and `<footer>` until the `<main>` content is available.
Once it is, it would push the `<footer>` down.

Does that make sense?

**Comment by mattiapontonio** [comment] 2021-01-24 13:45
Make sense.
I hate ADS 🙅‍♂️
Anyway if You curl the URL the HTML seems ok.
So the bug could be in some JavaScript.
I would Need to see the changes in HTML but i can't now.
https://reqbin.com/curl

**Comment by peterbe** [comment] 2021-01-25 18:14
Can we close this?

**Comment by mattiapontonio** [comment] 2021-01-25 18:45
Happens (not always) that i click on this link
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast#examples

And this is what i see
![Screenshot_20210125-194333.png](https://user-images.githubusercontent.com/44380480/105751037-c5bfde00-5f45-11eb-81f3-bbc7fde77834.png)

I think it's the main issue.

**Comment by mattiapontonio** [comment] 2021-01-25 22:41
But are the tests as if it were a browser in the project?

**Closed** 2021-01-26 11:14 UTC
